/**
 * @file eos_album.c
 * @brief Album - native C photo viewer with a lazy file manager
 *
 * - On enter: reads /sdcard/history/album/history.txt; if it holds a valid
 *   image path, that image opens directly. Otherwise the file manager opens.
 * - File manager (like TextHub FM): rooted at /sdcard/album/, lazy-loads the
 *   directory tree on demand, lists only directories and images (.jpg/.jpeg/
 *   .png), no thumbnails. Tap a folder to expand/collapse, tap an image to
 *   open it. Wide rows (36px) for comfortable reading.
 * - Viewer: prev/next arrows, tap to zoom, drag to pan, trash to delete,
 *   counter bottom-left, FM button bottom-right. English only.
 *
 * - JPEG: decoded to RGB565 with the bundled TJpgDec (streamed from SD,
 *         output capped at ALBUM_DECODE_MAX per side to stay OOM-safe).
 * - PNG: decoded by LVGL (LodePNG) from path, dimension pre-checked.
 */

#include "eos_album.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#include "eos_log.h"
#include "eos_config.h"
#include "eos_mem.h"
#include "eos_activity.h"
#include "eos_service_storage.h"
#include "eos_storage_paths.h"
#include "eos_font.h"
#include "eos_icon.h"
#include "ui/system/eos_round_clip.h" /* eos_round_clip() */
#include "lvgl.h"

#include "tjpgd/tjpgd.h" /* bundled TJpgDec (RGB565, scale 1/2/4/8) */

#define EOS_LOG_TAG "Album"

/* ------------------------------------------------------------------ */
/* Config                                                             */
/* ------------------------------------------------------------------ */

#define ALBUM_DIR          "/sdcard/album/"
#define ALBUM_HIST_DIR     "/sdcard/history/album/"
#define ALBUM_HIST_FILE    "/sdcard/history/album/history.txt"
#define ALBUM_MAX          256           /* viewer list cap (== FM_MAX_CHILD) */
#define FM_EXP_MAX         3             /* remembered expanded FM dirs (newest 3) */
#define ALBUM_IMG_MAX      150           /* fit box (px) for the image        */
#define ALBUM_DECODE_MAX   1024          /* JPEG decode cap per side (px)     */
#define ALBUM_PNG_MAX      1024          /* PNG side cap (LVGL decodes full)  */

/* Pre-encoded assets generated by scripts/album_optimize.py live in hidden
 * folders NEXT to each image (see _thumb_path/_tiles_dir): a whole package
 * is a single folder you drop anywhere under /sdcard/album/. */
#define ALBUM_BIN_MAGIC    0x19          /* LVGL image header magic   */
#define ALBUM_BIN_CF       0x12          /* LV_COLOR_FORMAT_RGB565    */
#define ALBUM_VIEW         240           /* viewport px (== screen)   */
#define ALBUM_TILE_MAX     16            /* tile slots (4x4 worst)    */

/* File manager (lazy tree) */
#define FM_MAX_CHILD       256           /* max entries read per directory     */
#define FM_MAX_VISIBLE     120           /* max rows rendered at once          */
#define FM_ROW_H           36            /* row height (spacious)              */
#define FM_DEPTH_MAX       6             /* max tree depth                     */

#define ALBUM_NAME_W       132           /* scrolling name label width      */
#define ALBUM_WORK_SIZE    8192          /* TJpgDec working pool (PSRAM)    */

#define _UI_BG        0x12121A
#define _UI_BTN_BG    0x1E1E2E
#define _UI_CAPSULE   0x34343F   /* bottom action capsule (light grey) */
#define _UI_PANEL     0x1A1A24
#define _UI_TEXT      0xFFFFFF
#define _UI_DIM       0x8A8AA0
#define _UI_ACCENT    0x6FA8FF

/* ------------------------------------------------------------------ */
/* State                                                              */
/* ------------------------------------------------------------------ */

typedef struct {
    eos_file_t fp;
    uint8_t   *out;
    uint16_t   out_w;
} _dec_ctx_t;

static eos_activity_t *s_act;
static lv_obj_t *s_root, *s_img, *s_name, *s_counter, *s_msg;
static lv_obj_t *s_prev_btn, *s_next_btn;
static lv_obj_t *s_capsule, *s_trash_btn, *s_fm_btn;   /* bottom capsule bar */

/* generated by scripts/icon/webp2c.py (compiled into the firmware) */
extern const lv_image_dsc_t eos_icon_fm;
extern const lv_image_dsc_t eos_icon_delete;

static int  s_img_w = 0, s_img_h = 0;   /* current image display size (thumb) */

static char (*s_paths)[EOS_FS_PATH_MAX]; /* viewer list of full paths (PSRAM) */
static int   s_count;
static int   s_index;
static bool  s_restore_miss;   /* 恢复的历史图不在 viewer 列表:显示第一张但跳过覆盖记录 */

static uint8_t       *s_pixels;          /* current thumb bin / JPEG decode buffer */
static lv_image_dsc_t s_dsc;

/* 1:1 tile browse state (tap enters, tap exits, drag pans) */
typedef struct {
    uint8_t        *pixels;              /* PSRAM tile pixels (owned) */
    lv_obj_t       *img;                 /* lv_image child of s_canvas */
    lv_image_dsc_t  dsc;                 /* persistent dsc (src keeps ptr) */
    uint8_t         c, r;                /* grid coord */
    uint8_t         w, h;                /* actual tile size (edge tiles) */
    bool            used;
} _tile_t;

static lv_obj_t    *s_canvas;            /* tile canvas (fullscreen 240x240) */
static lv_obj_t    *s_tile_badge;        /* "1:1" indicator */
static _tile_t      s_tiles[ALBUM_TILE_MAX];
static bool         s_tile_mode;         /* 1:1 browse active */
static int  s_orig_w = 0, s_orig_h = 0; /* original image size (from meta) */
static int  s_tcols = 0, s_trows = 0;    /* tile grid */
static int  s_ts = ALBUM_VIEW;           /* tile edge (from meta, default 240) */
static int  s_view_x = 0, s_view_y = 0;  /* viewport origin in original px */

/* File manager node (lazy-loaded tree, children are one array) */
typedef struct _fm_node_t
{
    char name[EOS_FS_NAME_MAX];
    char path[EOS_FS_PATH_MAX];
    bool is_dir;
    bool loaded;
    bool expanded;
    int  depth;
    int  child_count;
    struct _fm_node_t *children; /* malloc'd array, freed with subtree */
} _fm_node_t;

typedef struct
{
    _fm_node_t *node;
    int         depth;
} _fm_item_t;

static bool s_fm_open;
static lv_obj_t *s_fm_mask, *s_fm_panel, *s_fm_title, *s_fm_list;
static _fm_node_t *s_fm_root;
static _fm_item_t *s_fm_items;
static int s_fm_item_count;

/* ------------------------------------------------------------------ */
/* Helpers                                                            */
/* ------------------------------------------------------------------ */

static const char *_base(const char *path)
{
    const char *s = strrchr(path, '/');
    return s ? s + 1 : path;
}

static bool _is_image_ext(const char *name)
{
    const char *dot = strrchr(name, '.');
    if (!dot || dot[1] == '\0') return false;
    const char *e = dot + 1;
    return (strcasecmp(e, "jpg") == 0) || (strcasecmp(e, "jpeg") == 0) ||
           (strcasecmp(e, "png") == 0);
}

static bool _is_jpeg_ext(const char *name)
{
    const char *dot = strrchr(name, '.');
    if (!dot || dot[1] == '\0') return false;
    const char *e = dot + 1;
    return (strcasecmp(e, "jpg") == 0) || (strcasecmp(e, "jpeg") == 0);
}

/* Read PNG width/height from IHDR without decoding the whole file. */
static bool _png_dim(const char *path, uint32_t *w, uint32_t *h)
{
    eos_file_t fp = eos_storage_file_open_read(path);
    if (fp == EOS_FILE_INVALID) return false;

    uint8_t buf[24];
    if (eos_storage_file_read(fp, buf, sizeof(buf)) != (ssize_t)sizeof(buf)) {
        eos_storage_file_close(fp);
        return false;
    }
    eos_storage_file_close(fp);

    if (buf[0] != 0x89 || buf[1] != 'P' || buf[2] != 'N' || buf[3] != 'G') return false;

    *w = ((uint32_t)buf[16] << 24) | ((uint32_t)buf[17] << 16) |
         ((uint32_t)buf[18] << 8) | (uint32_t)buf[19];
    *h = ((uint32_t)buf[20] << 24) | ((uint32_t)buf[21] << 16) |
         ((uint32_t)buf[22] << 8) | (uint32_t)buf[23];
    return (*w > 0 && *h > 0);
}

/* ------------------------------------------------------------------ */
/* History: line 1 = last viewed image (resumed on enter, like TextHub);
 * line 2 = FM anchor (last image opened from the file manager, used to
 * restore the FM scroll position when the FM opens).                 */
/* ------------------------------------------------------------------ */

static char s_hist_img[EOS_FS_PATH_MAX];
static char s_fm_anchor[EOS_FS_PATH_MAX];

/* FM 展开记录:上次 FM 打开时展开过的目录(最多 FM_EXP_MAX 个,行尾最新) */
static char s_fm_exp[FM_EXP_MAX][EOS_FS_PATH_MAX];
static int  s_fm_exp_count;

static void _history_flush(void)
{
    char buf[EOS_FS_PATH_MAX * 6 + 16];
    int n = snprintf(buf, sizeof(buf), "%s\n%s\n", s_hist_img, s_fm_anchor);
    /* line 3: 最近展开的文件夹(最多 3 个,| 分隔,行尾最新) */
    for (int i = 0; i < s_fm_exp_count && n > 0 && n < (int)sizeof(buf); i++) {
        n += snprintf(buf + n, sizeof(buf) - (size_t)n, "%s%s",
                      i ? "|" : "", s_fm_exp[i]);
    }
    if (n < 0) n = 0;
    if ((size_t)n >= sizeof(buf)) n = (int)sizeof(buf) - 1;
    snprintf(buf + n, sizeof(buf) - (size_t)n, "\n");
    eos_storage_mkdir_recursive(ALBUM_HIST_DIR);
    eos_storage_write_file(ALBUM_HIST_FILE, buf, strlen(buf));
}

static void _write_history(const char *path)
{
    if (!path || !path[0]) return;
    strncpy(s_hist_img, path, sizeof(s_hist_img) - 1);
    s_hist_img[sizeof(s_hist_img) - 1] = '\0';
    _history_flush();
}

static void _write_fm_anchor(const char *path)
{
    if (!path || !path[0]) return;
    strncpy(s_fm_anchor, path, sizeof(s_fm_anchor) - 1);
    s_fm_anchor[sizeof(s_fm_anchor) - 1] = '\0';
    _history_flush();
}

/* 解析历史中的展开记录行:"p1|p2|p3"(行尾最新),只取最新 FM_EXP_MAX 个 */
static void _fm_exp_parse(const char *line)
{
    s_fm_exp_count = 0;
    if (!line || !line[0]) return;
    const char *tok = line;
    while (tok && *tok && s_fm_exp_count < FM_EXP_MAX) {
        const char *sep = strchr(tok, '|');
        size_t len = sep ? (size_t)(sep - tok) : strlen(tok);
        if (len > 0 && len < EOS_FS_PATH_MAX &&
            strncmp(tok, ALBUM_DIR, strlen(ALBUM_DIR)) == 0) {
            memcpy(s_fm_exp[s_fm_exp_count], tok, len);
            s_fm_exp[s_fm_exp_count][len] = '\0';
            s_fm_exp_count++;
        }
        if (!sep) break;
        tok = sep + 1;
    }
}

/* 展开一个目录:已存在则移到末尾(最新);超过 FM_EXP_MAX 个则丢弃最旧 */
static void _fm_exp_add(const char *path)
{
    if (!path || !path[0]) return;
    for (int i = 0; i < s_fm_exp_count; i++) {
        if (strcmp(s_fm_exp[i], path) == 0) {
            if (i != s_fm_exp_count - 1) {
                memmove(&s_fm_exp[i], &s_fm_exp[i + 1],
                        (size_t)(s_fm_exp_count - 1 - i) * sizeof(s_fm_exp[0]));
                s_fm_exp_count--;
                strncpy(s_fm_exp[s_fm_exp_count], path,
                        sizeof(s_fm_exp[0]) - 1);
                s_fm_exp[s_fm_exp_count][sizeof(s_fm_exp[0]) - 1] = '\0';
                s_fm_exp_count++;
            }
            _history_flush();
            return;
        }
    }
    if (s_fm_exp_count >= FM_EXP_MAX) {
        memmove(&s_fm_exp[0], &s_fm_exp[1],
                (size_t)(s_fm_exp_count - 1) * sizeof(s_fm_exp[0]));
        s_fm_exp_count--;
    }
    strncpy(s_fm_exp[s_fm_exp_count], path, sizeof(s_fm_exp[0]) - 1);
    s_fm_exp[s_fm_exp_count][sizeof(s_fm_exp[0]) - 1] = '\0';
    s_fm_exp_count++;
    _history_flush();
}

/* 收起一个目录:历史中包含才删除,否则不处理 */
static void _fm_exp_remove(const char *path)
{
    if (!path || !path[0]) return;
    for (int i = 0; i < s_fm_exp_count; i++) {
        if (strcmp(s_fm_exp[i], path) == 0) {
            memmove(&s_fm_exp[i], &s_fm_exp[i + 1],
                    (size_t)(s_fm_exp_count - 1 - i) * sizeof(s_fm_exp[0]));
            s_fm_exp_count--;
            _history_flush();
            return;
        }
    }
}

/* Trim trailing CR / spaces in place. Returns the trimmed length. */
static size_t _trim_line(char *s)
{
    size_t len = strlen(s);
    while (len > 0 && (s[len - 1] == '\r' || s[len - 1] == ' ')) {
        s[--len] = '\0';
    }
    return len;
}

/* Validate a history line as an existing image path under ALBUM_DIR. */
static bool _hist_line_valid(const char *s)
{
    return s && s[0] &&
           strncmp(s, ALBUM_DIR, strlen(ALBUM_DIR)) == 0 &&
           eos_storage_is_file(s);
}

static bool _read_history(char *out, size_t out_size)
{
    if (!out || out_size == 0) return false;
    out[0] = '\0';

    if (!eos_storage_is_file(ALBUM_HIST_FILE)) return false;

    char *content = eos_storage_read_file(ALBUM_HIST_FILE);
    if (!content) return false;

    /* line 1: last viewed image */
    char *nl = strchr(content, '\n');
    if (nl) *nl = '\0';
    _trim_line(content);
    bool valid = (strlen(content) > 0 && strlen(content) < out_size &&
                  _hist_line_valid(content));
    if (valid) {
        strncpy(out, content, out_size - 1);
        out[out_size - 1] = '\0';
    }

    /* line 2: FM anchor (absent on old single-line history files) */
    if (nl && nl[1] != '\0') {
        char *l2 = nl + 1;
        char *nl2 = strchr(l2, '\n');
        if (nl2) *nl2 = '\0';
        _trim_line(l2);
        if (_hist_line_valid(l2)) {
            strncpy(s_fm_anchor, l2, sizeof(s_fm_anchor) - 1);
            s_fm_anchor[sizeof(s_fm_anchor) - 1] = '\0';
        }
        /* line 3: 最近展开的文件夹(最多 3 个,| 分隔,行尾最新) */
        if (nl2 && nl2[1] != '\0') {
            char *l3 = nl2 + 1;
            char *nl3 = strchr(l3, '\n');
            if (nl3) *nl3 = '\0';
            _trim_line(l3);
            _fm_exp_parse(l3);
        }
    }
    eos_free(content);
    return valid;
}

/* ------------------------------------------------------------------ */
/* JPEG decode (TJpgDec, streamed from SD)                            */
/* ------------------------------------------------------------------ */

static size_t _jd_in(JDEC *jd, uint8_t *buf, size_t nd)
{
    _dec_ctx_t *c = (_dec_ctx_t *)jd->device;
    if (!buf) { /* skip nd bytes */
        uint32_t pos = 0;
        if (eos_storage_file_tell(c->fp, &pos) != EOS_OK) {
            EOS_LOG_E("Album: skip tell FAIL");
            return 0;
        }
        if (eos_storage_file_seek(c->fp, pos + nd) != EOS_OK) {
            EOS_LOG_E("Album: skip seek FAIL pos=%u nd=%u", pos, (unsigned)nd);
            return 0;
        }
        return nd;
    }
    ssize_t rd = eos_storage_file_read(c->fp, buf, nd);
    return rd > 0 ? (size_t)rd : 0;
}

static int _jd_out(JDEC *jd, void *bitmap, JRECT *rect)
{
    _dec_ctx_t *c = (_dec_ctx_t *)jd->device;
    if (!c->out) return 0;

    uint16_t bw = rect->right - rect->left + 1;
    uint32_t stride = (uint32_t)c->out_w * 2;
    const uint8_t *src = (const uint8_t *)bitmap;
    uint8_t *dst = c->out + ((uint32_t)rect->top * c->out_w + rect->left) * 2;

    for (uint16_t y = rect->top; y <= rect->bottom; y++) {
        memcpy(dst, src, bw * 2);
        src += bw * 2;
        dst += stride;
    }
    return 1; /* continue */
}

static bool _decode_jpeg(const char *path, lv_image_dsc_t *dsc)
{
    eos_file_t fp = eos_storage_file_open_read(path);
    if (fp == EOS_FILE_INVALID) {
        EOS_LOG_E("Album: open FAIL %s", path);
        return false;
    }
    EOS_LOG_I("Album: decode %s", path);

    /* TJpgDec working pool (huffman tables + MCU buffer), PSRAM to save IRAM */
    uint8_t *work = (uint8_t *)eos_malloc(ALBUM_WORK_SIZE);
    if (!work) {
        EOS_LOG_E("Album: work malloc FAIL size=%u", (unsigned)ALBUM_WORK_SIZE);
        eos_storage_file_close(fp);
        return false;
    }

    _dec_ctx_t ctx;
    ctx.fp    = fp;
    ctx.out   = NULL;
    ctx.out_w = 0;

    JDEC jd;
    JRESULT rc = jd_prepare(&jd, _jd_in, work, ALBUM_WORK_SIZE, &ctx);
    if (rc != JDR_OK) {
        EOS_LOG_E("Album: jd_prepare FAIL rc=%d", (int)rc);
        eos_free(work);
        eos_storage_file_close(fp);
        return false;
    }

    uint16_t w = jd.width, h = jd.height;
    /* TJpgDec scale = right shift count: 0=full, 1=1/2, 2=1/4, 3=1/8 (max) */
    uint8_t scale = 0;
    uint16_t ow = w, oh = h;
    while (scale < 3 && (ow > ALBUM_DECODE_MAX || oh > ALBUM_DECODE_MAX)) {
        scale++;
        ow >>= 1;
        oh >>= 1;
    }
    if (ow == 0 || oh == 0 || ow > ALBUM_DECODE_MAX || oh > ALBUM_DECODE_MAX) {
        EOS_LOG_E("Album: jpeg %ux%u too large even at 1/8", w, h);
        eos_free(work);
        eos_storage_file_close(fp);
        return false; /* too large even at 1/8 */
    }

    uint32_t npix = (uint32_t)ow * oh * 2;
    uint8_t *pix = (uint8_t *)eos_malloc(npix);
    if (!pix) {
        EOS_LOG_E("Album: pix malloc FAIL size=%u", (unsigned)npix);
        eos_free(work);
        eos_storage_file_close(fp);
        return false;
    }

    ctx.out   = pix;
    ctx.out_w = ow;

    EOS_LOG_I("Album: jpeg %ux%u scale=%u -> %ux%u", w, h, scale, ow, oh);

    JRESULT drc = jd_decomp(&jd, _jd_out, scale);
    if (drc != JDR_OK) {
        EOS_LOG_E("Album: jd_decomp FAIL rc=%d w=%u h=%u scale=%u", (int)drc, w, h, scale);
        eos_free(pix);
        eos_free(work);
        eos_storage_file_close(fp);
        return false;
    }

    eos_free(work);
    eos_storage_file_close(fp);

    memset(dsc, 0, sizeof(*dsc));
    dsc->header.magic  = LV_IMAGE_HEADER_MAGIC;
    dsc->header.cf     = LV_COLOR_FORMAT_RGB565;
    dsc->header.w      = ow;
    dsc->header.h      = oh;
    dsc->header.stride = ow * 2;
    dsc->data          = pix;
    dsc->data_size     = npix;
    return true;
}

/* ------------------------------------------------------------------ */
/* Viewer list: flat scan of ONE directory (no recursion)             */
/* ------------------------------------------------------------------ */

static int _cmp_path(const void *a, const void *b)
{
    const char *pa = _base((const char *)a);
    const char *pb = _base((const char *)b);
    return strcasecmp(pa, pb);
}

static int _load_dir_pics(const char *dir)
{
    if (s_paths) {
        eos_free(s_paths);
        s_paths = NULL;
    }
    s_count = 0;
    s_index = 0;

    if (!eos_storage_is_dir(dir)) return 0;

    s_paths = (char (*)[EOS_FS_PATH_MAX])eos_malloc(ALBUM_MAX * EOS_FS_PATH_MAX);
    if (!s_paths) return 0;

    eos_dir_t d = eos_storage_dir_open(dir);
    if (!d) return 0;

    char name[EOS_FS_NAME_MAX];
    while (s_count < ALBUM_MAX &&
           eos_storage_dir_read(d, name, sizeof(name)) == EOS_OK) {
        if (name[0] == '.') continue; /* skip dot entries */
        char full[EOS_FS_PATH_MAX];
        size_t dl = strlen(dir), nl = strlen(name);
        if (dl + 1 + nl + 1 > sizeof(full)) continue; /* path too long */
        memcpy(full, dir, dl);
        full[dl] = '/';
        strcpy(full + dl + 1, name);
        if (eos_storage_is_file(full) && _is_image_ext(name)) {
            strncpy(s_paths[s_count], full, EOS_FS_PATH_MAX - 1);
            s_paths[s_count][EOS_FS_PATH_MAX - 1] = '\0';
            s_count++;
        }
    }
    eos_storage_dir_close(d);

    if (s_count > 1) {
        qsort(s_paths, s_count, EOS_FS_PATH_MAX, _cmp_path);
    }
    return s_count;
}

static void _show_current(void);

/* Open a specific image: switch to its directory, locate it, show it. */
static bool _open_image_path(const char *path)
{
    if (!path || !path[0]) return false;

    /* derive directory from the path */
    char dir[EOS_FS_PATH_MAX];
    const char *slash = strrchr(path, '/');
    if (!slash) return false;
    size_t dl = (size_t)(slash - path);
    if (dl == 0) return false;
    if (dl >= sizeof(dir)) return false;
    memcpy(dir, path, dl);
    dir[dl] = '\0';

    if (_load_dir_pics(dir) <= 0) {
        return false;
    }

    /* locate index of the opened path */
    s_restore_miss = false;
    bool found = false;
    for (int i = 0; i < s_count; i++) {
        if (strcmp(s_paths[i], path) == 0) {
            s_index = i;
            found = true;
            break;
        }
    }
    /* 目录图片数达到 ALBUM_MAX 上限被截断时,精确路径可能不在列表里:
     * 退回 basename 匹配(同目录下文件名唯一,安全) */
    if (!found) {
        const char *want = _base(path);
        for (int i = 0; i < s_count; i++) {
            if (strcasecmp(_base(s_paths[i]), want) == 0) {
                s_index = i;
                found = true;
                break;
            }
        }
    }
    /* 仍找不到:显示第一张,但不覆盖上次的 history 记录 */
    if (!found) {
        s_index = 0;
        s_restore_miss = true;
    }
    _show_current();
    return true;
}

/* ------------------------------------------------------------------ */
/* Display                                                            */
/* ------------------------------------------------------------------ */

static uint32_t _fit_scale(uint32_t w, uint32_t h)
{
    uint32_t sx = (ALBUM_IMG_MAX * 256) / (w ? w : 1);
    uint32_t sy = (ALBUM_IMG_MAX * 256) / (h ? h : 1);
    uint32_t s = sx < sy ? sx : sy;
    if (s < 1) s = 1;
    if (s > 1024) s = 1024;
    return s;
}

/* Fit the thumbnail image into the display box, centered. The 1:1 browse
 * mode (tiles) handles magnification, so no zoom/pan here. */
static void _apply_view(void)
{
    if (!s_img || s_img_w <= 0 || s_img_h <= 0) return;
    lv_image_set_scale(s_img, _fit_scale(s_img_w, s_img_h));
    lv_obj_center(s_img);
}

static void _free_pixels(void)
{
    if (s_pixels) {
        eos_free(s_pixels);
        s_pixels = NULL;
    }
}

/* ------------------------------------------------------------------ */
/* Pre-encoded assets: thumbnail bin + 1:1 tile grid                   */
/* ------------------------------------------------------------------ */

/* Assets travel WITH each image, in hidden folders next to it, so a whole
 * package (one scripts/album_optimize.py run) is a single folder you can
 * drop anywhere under /sdcard/album/:
 *   <img dir>/.thumb/<base>.bin           : RGB565 LVGL bin, fitted <=240px
 *   <img dir>/.tiles/<base>/meta.txt      : "orig_w orig_h tile cols rows"
 *   <img dir>/.tiles/<base>/tile_<c>_<r>.bin
 * The file manager hides dot-directories, so these never show up. */

/* "/a/b/photo.jpg" -> dir="/a/b", base="photo" */
static void _dir_base(const char *img, char *dir, size_t dsz, char *base, size_t bsz)
{
    const char *slash = strrchr(img, '/');
    size_t dl = slash ? (size_t)(slash - img) : 0;
    if (dl >= dsz) dl = dsz - 1;
    memcpy(dir, img, dl);
    dir[dl] = '\0';
    const char *bn = slash ? slash + 1 : img;
    snprintf(base, bsz, "%s", bn);
    char *dot = strrchr(base, '.');
    if (dot) *dot = '\0'; /* strip extension only */
}

static void _thumb_path(const char *img, char *out, size_t sz)
{
    char dir[EOS_FS_PATH_MAX], base[EOS_FS_PATH_MAX];
    _dir_base(img, dir, sizeof(dir), base, sizeof(base));
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-truncation"
    /* gcc over-estimates `base` length; ALBUM_PATH_BUF is sized for the real
     * (dir + .thumb/ + base + .bin) upper bound. */
    snprintf(out, sz, "%s/.thumb/%s.bin", dir, base);
#pragma GCC diagnostic pop
}

static void _tiles_dir(const char *img, char *out, size_t sz)
{
    char dir[EOS_FS_PATH_MAX], base[EOS_FS_PATH_MAX];
    _dir_base(img, dir, sizeof(dir), base, sizeof(base));
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-truncation"
    snprintf(out, sz, "%s/.tiles/%s", dir, base);
#pragma GCC diagnostic pop
}

/* safe path scratch buffer: longest album path (EOS_FS_PATH_MAX) + mirror
 * prefix (/sdcard/album_thumbnail or /sdcard/album_tiles, +7) + suffix
 * (/tile_<c>_<r>.bin or /meta.txt) — keep generous so the (conservative)
 * -Wformat-truncation analysis stays quiet. */
#define ALBUM_PATH_BUF (EOS_FS_PATH_MAX + 64)

/* Read an LVGL bin file (12B header + pixels) into a fresh PSRAM buffer.
 * On success fills `dsc` (data points into the buffer) and returns the
 * buffer base in *alloc — free it with eos_free(). */
static bool _load_bin(const char *path, lv_image_dsc_t *dsc, uint8_t **alloc,
                      uint32_t *npix_out)
{
    eos_file_t fp = eos_storage_file_open_read(path);
    if (fp == EOS_FILE_INVALID) return false;

    uint8_t hdr[12]; /* magic|cf|flags(2)|w(2)|h(2)|stride(2)|reserved(2) */
    if (eos_storage_file_read(fp, hdr, sizeof(hdr)) != (ssize_t)sizeof(hdr)) {
        eos_storage_file_close(fp);
        return false;
    }
    if (hdr[0] != ALBUM_BIN_MAGIC || hdr[1] != ALBUM_BIN_CF) {
        eos_storage_file_close(fp);
        return false;
    }
    uint16_t w = (uint16_t)(hdr[4] | (hdr[5] << 8));
    uint16_t h = (uint16_t)(hdr[6] | (hdr[7] << 8));
    if (w == 0 || h == 0 || w > 2048 || h > 2048) {
        eos_storage_file_close(fp);
        return false;
    }
    uint32_t npix = (uint32_t)w * h * 2;
    uint8_t *buf = (uint8_t *)eos_malloc(12 + npix);
    if (!buf) {
        eos_storage_file_close(fp);
        return false;
    }
    memcpy(buf, hdr, sizeof(hdr));
    if (eos_storage_file_read(fp, buf + sizeof(hdr), npix) != (ssize_t)npix) {
        eos_free(buf);
        eos_storage_file_close(fp);
        return false;
    }
    eos_storage_file_close(fp);

    memset(dsc, 0, sizeof(*dsc));
    dsc->header.magic  = LV_IMAGE_HEADER_MAGIC;
    dsc->header.cf     = LV_COLOR_FORMAT_RGB565;
    dsc->header.w      = w;
    dsc->header.h      = h;
    dsc->header.stride = w * 2;
    dsc->data          = buf + sizeof(hdr);
    dsc->data_size     = npix;
    *alloc = buf;
    if (npix_out) *npix_out = npix;
    return true;
}

/* Thumbnail state: try the pre-encoded RGB565 bin first (zero decode,
 * ~112 KB buffer vs ~1.1 MB JPEG). Falls back to JPEG/PNG decode by caller. */
static bool _show_thumb(const char *path)
{
    char tp[ALBUM_PATH_BUF];
    _thumb_path(path, tp, sizeof(tp));
    uint8_t *buf = NULL;
    if (!_load_bin(tp, &s_dsc, &buf, NULL)) return false;
    eos_free(s_pixels);
    s_pixels = buf;                    /* keep alive until next show */
    s_img_w = s_dsc.header.w;
    s_img_h = s_dsc.header.h;
    lv_image_set_src(s_img, &s_dsc);
    lv_image_set_pivot(s_img, s_dsc.header.w / 2, s_dsc.header.h / 2);
    return true;
}

/* --- 1:1 tile browse -------------------------------------------------- */

static void _img_event_cb(lv_event_t *e);   /* defined below (gestures) */
static void _show_msg(const char *txt);     /* defined below */

static void _ui_controls(bool vis)
{
    lv_obj_t *objs[] = { s_prev_btn, s_next_btn, s_capsule, s_name };
    for (size_t i = 0; i < sizeof(objs) / sizeof(objs[0]); i++) {
        if (!objs[i]) continue;
        if (vis) lv_obj_remove_flag(objs[i], LV_OBJ_FLAG_HIDDEN);
        else lv_obj_add_flag(objs[i], LV_OBJ_FLAG_HIDDEN);
    }
}

static _tile_t *_tile_find(int c, int r)
{
    for (int i = 0; i < ALBUM_TILE_MAX; i++) {
        if (s_tiles[i].used && s_tiles[i].c == c && s_tiles[i].r == r)
            return &s_tiles[i];
    }
    return NULL;
}

static void _tile_unload(_tile_t *t)
{
    if (!t->used) return;
    if (t->img) {
        lv_obj_delete(t->img);
        t->img = NULL;
    }
    if (t->pixels) {
        eos_free(t->pixels);           /* give PSRAM back immediately */
        t->pixels = NULL;
    }
    t->used = false;
}

static void _tile_load(int c, int r)
{
    char dir[ALBUM_PATH_BUF], path[ALBUM_PATH_BUF];
    _tiles_dir(s_paths[s_index], dir, sizeof(dir));
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-truncation"
    snprintf(path, sizeof(path), "%s/tile_%d_%d.bin", dir, c, r);
#pragma GCC diagnostic pop

    lv_image_dsc_t dsc;                /* local: copied into the slot below */
    uint8_t *buf = NULL;
    if (!_load_bin(path, &dsc, &buf, NULL)) {
        EOS_LOG_W("Album: tile %d,%d load FAIL", c, r);
        return;
    }
    _tile_t *t = NULL;
    for (int i = 0; i < ALBUM_TILE_MAX; i++) {
        if (!s_tiles[i].used) { t = &s_tiles[i]; break; }
    }
    if (!t) {                          /* no slot: drop, memory stays bounded */
        eos_free(buf);
        EOS_LOG_W("Album: tile slot full (%d,%d)", c, r);
        return;
    }
    t->c = c;
    t->r = r;
    t->w = (uint8_t)dsc.header.w;
    t->h = (uint8_t)dsc.header.h;
    t->pixels = buf;
    t->dsc = dsc;                      /* data points into buf+12 */
    t->used = true;
    t->img = lv_image_create(s_canvas);
    lv_image_set_src(t->img, &t->dsc);
    lv_obj_set_pos(t->img, c * s_ts - s_view_x, r * s_ts - s_view_y);
}

/* Load the tiles that cover the viewport (+1-tile margin) and drop the
 * rest. Called after every viewport move; keeps the working set small. */
static void _tile_refresh(void)
{
    if (!s_tile_mode || !s_canvas || s_ts <= 0) return;

    int c0 = s_view_x / s_ts;
    int c1 = (s_view_x + ALBUM_VIEW - 1) / s_ts;
    int r0 = s_view_y / s_ts;
    int r1 = (s_view_y + ALBUM_VIEW - 1) / s_ts;
    if (c0 > 0) c0--;
    if (r0 > 0) r0--;
    if (c1 < s_tcols - 1) c1++;
    if (r1 < s_trows - 1) r1++;

    /* Same tile window as the previous call -> only reposition, skip the
     * SD load/unload (called on every PRESSING sample while panning).
     * "has_tiles" guards the first call after (re-)entering 1:1 so a
     * coincidentally equal window can never skip the initial load. */
    static int last_c0 = -1, last_c1 = -1, last_r0 = -1, last_r1 = -1;
    bool has_tiles = false;
    for (int i = 0; i < ALBUM_TILE_MAX; i++) {
        if (s_tiles[i].used) { has_tiles = true; break; }
    }
    if (has_tiles && last_c0 == c0 && last_c1 == c1 && last_r0 == r0 && last_r1 == r1) {
        for (int i = 0; i < ALBUM_TILE_MAX; i++) {
            if (!s_tiles[i].used) continue;
            lv_obj_set_pos(s_tiles[i].img,
                           s_tiles[i].c * s_ts - s_view_x,
                           s_tiles[i].r * s_ts - s_view_y);
        }
        return;
    }
    last_c0 = c0;
    last_c1 = c1;
    last_r0 = r0;
    last_r1 = r1;

    for (int i = 0; i < ALBUM_TILE_MAX; i++) {
        if (!s_tiles[i].used) continue;
        if (s_tiles[i].c < c0 || s_tiles[i].c > c1 ||
            s_tiles[i].r < r0 || s_tiles[i].r > r1) {
            _tile_unload(&s_tiles[i]);
        }
    }
    for (int c = c0; c <= c1; c++) {
        for (int r = r0; r <= r1; r++) {
            if (!_tile_find(c, r)) _tile_load(c, r);
        }
    }
    for (int i = 0; i < ALBUM_TILE_MAX; i++) {
        if (!s_tiles[i].used) continue;
        lv_obj_set_pos(s_tiles[i].img,
                       s_tiles[i].c * s_ts - s_view_x,
                       s_tiles[i].r * s_ts - s_view_y);
    }
}

static void _tile_exit(void);

static void _tile_enter(int tap_x, int tap_y)
{
    if (s_tile_mode || s_count <= 0) return;

    char dir[ALBUM_PATH_BUF], mpath[ALBUM_PATH_BUF];
    _tiles_dir(s_paths[s_index], dir, sizeof(dir));
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-truncation"
    snprintf(mpath, sizeof(mpath), "%s/meta.txt", dir);
#pragma GCC diagnostic pop
    char *meta = eos_storage_read_file(mpath);
    if (!meta) {
        _show_msg("NO HD DATA\nRun album_optimize.py");
        return;
    }
    int ow = 0, oh = 0, ts = 0, cols = 0, rows = 0;
    int parsed = sscanf(meta, "%d %d %d %d %d", &ow, &oh, &ts, &cols, &rows);
    eos_free(meta);
    if (parsed != 5 || ts <= 0 || cols <= 0 || rows <= 0 || ow <= 0 || oh <= 0) {
        _show_msg("NO HD DATA\nRun album_optimize.py");
        return;
    }
    /* 1:1 on an image no bigger than the viewport is pointless */
    if (ow <= ALBUM_VIEW && oh <= ALBUM_VIEW) return;

    s_orig_w = ow;
    s_orig_h = oh;
    s_tcols  = cols;
    s_trows  = rows;
    s_ts     = ts;

    /* fullscreen canvas above the buttons */
    s_canvas = lv_obj_create(s_root);
    lv_obj_remove_style_all(s_canvas);
    lv_obj_set_size(s_canvas, ALBUM_VIEW, ALBUM_VIEW);
    lv_obj_set_pos(s_canvas, 0, 0);
    lv_obj_remove_flag(s_canvas, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(s_canvas, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(s_canvas, _img_event_cb, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(s_canvas, _img_event_cb, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(s_canvas, _img_event_cb, LV_EVENT_RELEASED, NULL);

    s_tile_badge = lv_label_create(s_root);
    lv_obj_set_style_text_color(s_tile_badge, lv_color_hex(_UI_TEXT), 0);
    lv_obj_set_style_text_font(s_tile_badge, &lv_font_montserrat_12, 0);
    lv_label_set_text(s_tile_badge, "1:1");
    lv_obj_align(s_tile_badge, LV_ALIGN_TOP_RIGHT, -8, 24);

    /* hide chrome, start at image center */
    _ui_controls(false);
    lv_obj_add_flag(s_img, LV_OBJ_FLAG_HIDDEN);
    s_tile_mode = true;

    /* Tap-where-you-zoom: map the tap point (screen coords) through the
     * fitted thumbnail rectangle into original-image pixels and centre the
     * viewport there (clamped to the image bounds). Falls back to centre. */
    int ox = ow / 2, oy = oh / 2;
    if (s_img_w > 0 && s_img_h > 0) {
        uint32_t sc = _fit_scale(s_img_w, s_img_h);
        int wd = (int)((s_img_w * sc) >> 8);   /* on-screen size */
        int hd = (int)((s_img_h * sc) >> 8);
        if (wd > 0 && hd > 0) {
            int rx = tap_x - (ALBUM_VIEW - wd) / 2;
            int ry = tap_y - (ALBUM_VIEW - hd) / 2;
            if (rx < 0) rx = 0;
            else if (rx > wd) rx = wd;
            if (ry < 0) ry = 0;
            else if (ry > hd) ry = hd;
            ox = (rx * ow + wd / 2) / wd;      /* round to nearest px */
            oy = (ry * oh + hd / 2) / hd;
        }
    }
    int mx = ow - ALBUM_VIEW, my = oh - ALBUM_VIEW;
    if (mx < 0) mx = 0;
    if (my < 0) my = 0;
    s_view_x = ox - ALBUM_VIEW / 2;
    s_view_y = oy - ALBUM_VIEW / 2;
    if (s_view_x < 0) s_view_x = 0;
    if (s_view_x > mx) s_view_x = mx;
    if (s_view_y < 0) s_view_y = 0;
    if (s_view_y > my) s_view_y = my;
    _tile_refresh();
    EOS_LOG_I("Album: 1:1 %dx%d grid %dx%d ts=%d view=%d,%d",
              ow, oh, cols, rows, ts, s_view_x, s_view_y);
}

static void _tile_exit(void)
{
    if (!s_tile_mode && !s_canvas) return;
    s_tile_mode = false;
    for (int i = 0; i < ALBUM_TILE_MAX; i++) _tile_unload(&s_tiles[i]);
    if (s_canvas) {
        lv_obj_delete(s_canvas);
        s_canvas = NULL;
    }
    if (s_tile_badge) {
        lv_obj_delete(s_tile_badge);
        s_tile_badge = NULL;
    }
    _ui_controls(true);
    lv_obj_remove_flag(s_img, LV_OBJ_FLAG_HIDDEN);
    if (s_img_w > 0) _apply_view();
}

static void _show_msg(const char *txt)
{
    if (!s_msg) return;
    lv_label_set_text(s_msg, txt);
    lv_obj_remove_flag(s_msg, LV_OBJ_FLAG_HIDDEN);
    if (s_img) lv_obj_add_flag(s_img, LV_OBJ_FLAG_HIDDEN);
}

static void _clear_msg(void)
{
    if (!s_msg) return;
    lv_obj_add_flag(s_msg, LV_OBJ_FLAG_HIDDEN);
    if (s_img) lv_obj_remove_flag(s_img, LV_OBJ_FLAG_HIDDEN);
}

static void _show_empty(void)
{
    _tile_exit();
    _free_pixels();
    lv_image_set_src(s_img, NULL);
    lv_label_set_text(s_name, "");
    lv_label_set_text(s_counter, "0/0");
    _show_msg("NO IMAGES\nTap FM to browse");
}

static void _show_index(void)
{
    char buf[24];
    snprintf(buf, sizeof(buf), "%d/%d", s_index + 1, s_count);
    lv_label_set_text(s_counter, buf);
}

static void _show_name(void)
{
    const char *b = _base(s_paths[s_index]);
    lv_label_set_text(s_name, b);
    lv_label_set_long_mode(s_name, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
}

static void _show_current(void)
{
    if (s_count <= 0) {
        _tile_exit();
        _show_empty();
        return;
    }
    if (s_index < 0) s_index = 0;
    if (s_index >= s_count) s_index = s_count - 1;

    _tile_exit();   /* leave 1:1 browse before switching images */
    _free_pixels(); /* release previous buffer first */
    _clear_msg();

    const char *path = s_paths[s_index];

    /* preferred: pre-encoded RGB565 thumbnail (zero decode) */
    if (_show_thumb(path)) {
        lv_image_set_scale(s_img, _fit_scale(s_img_w, s_img_h));
    } else if (_is_jpeg_ext(path)) {
        if (_decode_jpeg(path, &s_dsc)) {
            s_pixels = (uint8_t *)s_dsc.data; /* keep alive until next show */
            s_img_w = s_dsc.header.w;
            s_img_h = s_dsc.header.h;
            lv_image_set_src(s_img, &s_dsc);
            lv_image_set_pivot(s_img, s_dsc.header.w / 2, s_dsc.header.h / 2);
            lv_image_set_scale(s_img, _fit_scale(s_dsc.header.w, s_dsc.header.h));
        } else {
            lv_image_set_src(s_img, NULL);
            s_img_w = s_img_h = 0;
            _show_msg("DECODE FAIL");
        }
    } else { /* PNG -> LVGL (LodePNG) */
        uint32_t pw = 0, ph = 0;
        if (_png_dim(path, &pw, &ph)) {
            if (pw > ALBUM_PNG_MAX || ph > ALBUM_PNG_MAX) {
                lv_image_set_src(s_img, NULL);
                s_img_w = s_img_h = 0;
                _show_msg("TOO LARGE");
            } else {
                lv_image_header_t hdr;
                if (lv_image_decoder_get_info(path, &hdr) == LV_RESULT_OK && hdr.w > 0) {
                    s_img_w = hdr.w;
                    s_img_h = hdr.h;
                    lv_image_set_src(s_img, path);
                    lv_image_set_pivot(s_img, hdr.w / 2, hdr.h / 2);
                    lv_image_set_scale(s_img, _fit_scale(hdr.w, hdr.h));
                } else {
                    lv_image_set_src(s_img, NULL);
                    s_img_w = s_img_h = 0;
                    _show_msg("DECODE FAIL");
                }
            }
        } else {
            lv_image_set_src(s_img, NULL);
            s_img_w = s_img_h = 0;
            _show_msg("DECODE FAIL");
        }
    }

    lv_obj_center(s_img);
    _apply_view();
    _show_name();
    _show_index();

    /* remember last viewed image for next launch.
     * 恢复时目标图不在 viewer 列表(s_restore_miss)则跳过本次写入,
     * 避免用错误的"第一张"覆盖历史记录;用户后续切换图片后恢复正常记录。 */
    if (s_restore_miss) {
        s_restore_miss = false;
    } else {
        _write_history(s_paths[s_index]);
    }
}

/* ------------------------------------------------------------------ */
/* File manager (lazy tree, no thumbnails)                            */
/* ------------------------------------------------------------------ */

static void _fm_children_free(_fm_node_t *n)
{
    if (!n) return;
    if (n->children) {
        for (int i = 0; i < n->child_count; i++) {
            _fm_children_free(&n->children[i]);
        }
        eos_free(n->children);
        n->children = NULL;
    }
    n->child_count = 0;
    n->loaded = false;
    n->expanded = false;
}

static int _fm_cmp(const void *a, const void *b)
{
    const _fm_node_t *na = (const _fm_node_t *)a;
    const _fm_node_t *nb = (const _fm_node_t *)b;
    if (na->is_dir != nb->is_dir) return nb->is_dir - na->is_dir;
    return strcasecmp(na->name, nb->name);
}

/* Lazy load: read one directory into an array of children nodes. */
static bool _fm_node_load(_fm_node_t *n)
{
    if (n->loaded) return true;
    if (n->depth >= FM_DEPTH_MAX) { n->loaded = true; return false; }

    /* pass 1: count entries */
    eos_dir_t d = eos_storage_dir_open(n->path);
    if (!d) {
        n->loaded = true;
        EOS_LOG_W("Album: opendir FAIL %s", n->path);
        return false;
    }
    int cnt = 0;
    char name[EOS_FS_NAME_MAX];
    while (eos_storage_dir_read(d, name, sizeof(name)) == EOS_OK) {
        if (name[0] == '\0' || name[0] == '.') continue;
        if (++cnt > FM_MAX_CHILD) { cnt = FM_MAX_CHILD; break; }
    }
    eos_storage_dir_close(d);
    EOS_LOG_I("Album: dir %s raw=%d", n->path, cnt);

    if (cnt == 0) { n->loaded = true; return false; }

    _fm_node_t *arr = (_fm_node_t *)eos_malloc_zeroed((size_t)cnt * sizeof(_fm_node_t));
    if (!arr) { n->loaded = true; return false; }

    /* pass 2: fill, keeping only directories + images */
    d = eos_storage_dir_open(n->path);
    if (!d) { eos_free(arr); n->loaded = true; return false; }
    int i = 0;
    while (i < cnt && eos_storage_dir_read(d, name, sizeof(name)) == EOS_OK) {
        if (name[0] == '\0' || name[0] == '.') continue;
        char full[EOS_FS_PATH_MAX];
        size_t dl = strlen(n->path), nl = strlen(name);
        if (dl + 1 + nl + 1 > sizeof(full)) continue;
        memcpy(full, n->path, dl);
        full[dl] = '/';
        strcpy(full + dl + 1, name);

        bool is_dir = eos_storage_is_dir(full);
        if (!is_dir && !_is_image_ext(name)) continue; /* only dirs + images */

        _fm_node_t *c = &arr[i];
        strncpy(c->name, name, sizeof(c->name) - 1);
        c->name[sizeof(c->name) - 1] = '\0';
        strncpy(c->path, full, sizeof(c->path) - 1);
        c->path[sizeof(c->path) - 1] = '\0';
        c->is_dir = is_dir;
        c->depth  = n->depth + 1;
        i++;
        if (i >= FM_MAX_CHILD) break;
    }
    eos_storage_dir_close(d);

    n->children = arr;
    n->child_count = i;
    n->loaded = true;
    if (i > 1) {
        qsort(arr, (size_t)i, sizeof(_fm_node_t), _fm_cmp);
    }
    EOS_LOG_I("Album: dir %s children=%d", n->path, i);
    return i > 0;
}

static void _fm_build_items(_fm_node_t *n, int depth, int *cnt)
{
    if (*cnt >= FM_MAX_VISIBLE) return;
    if (!n) return;
    s_fm_items[*cnt].node = n;
    s_fm_items[*cnt].depth = depth;
    (*cnt)++;

    /* only directories recurse (images are leaves: click opens them) */
    if (n->is_dir && n->expanded && n->children) {
        for (int i = 0; i < n->child_count && *cnt < FM_MAX_VISIBLE; i++) {
            _fm_build_items(&n->children[i], depth + 1, cnt);
        }
    }
}

static void _fm_row_cb(lv_event_t *e); /* fwd decl */
static void _fm_arrow_cb(lv_event_t *e);

static void _fm_rebuild(void)
{
    if (!s_fm_open || !s_fm_list) {
        EOS_LOG_W("Album: rebuild skip open=%d list=%p", s_fm_open, (void *)s_fm_list);
        return;
    }

    /* 保存滚动位置:clean 后内容高度归零,LVGL 会把 scroll 清零导致
     * 展开/收起后跳回列表顶部 */
    int32_t scroll_y = lv_obj_get_scroll_y(s_fm_list);

    /* clear old rows */
    lv_obj_clean(s_fm_list);

    if (!s_fm_root) {
        EOS_LOG_E("Album: rebuild root NULL");
        return;
    }
    if (!s_fm_root->loaded) _fm_node_load(s_fm_root);

    if (!s_fm_items) {
        s_fm_items = (_fm_item_t *)eos_malloc(FM_MAX_VISIBLE * sizeof(_fm_item_t));
        if (!s_fm_items) {
            EOS_LOG_E("Album: items alloc FAIL size=%u",
                      (unsigned)(FM_MAX_VISIBLE * sizeof(_fm_item_t)));
            return;
        }
    }
    int cnt = 0;
    _fm_build_items(s_fm_root, 0, &cnt);
    s_fm_item_count = cnt;

    int list_w = lv_obj_get_width(s_fm_list);
    if (list_w <= 0) list_w = 196;
    int name_w = list_w - 30 - 8; /* indent room + arrow */

    for (int i = 0; i < cnt; i++) {
        _fm_node_t *node = s_fm_items[i].node;
        int depth = s_fm_items[i].depth;

        lv_obj_t *row = lv_button_create(s_fm_list);
        lv_obj_remove_style_all(row);
        lv_obj_set_size(row, list_w, FM_ROW_H);
        /* rows must not be scroll targets or they swallow the drag gesture */
        lv_obj_clear_flag(row, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_color(row, lv_color_hex(_UI_TEXT), 0);
        lv_obj_set_style_bg_opa(row, i % 2 ? 10 : 0, 0);   /* faint zebra */
        lv_obj_set_style_radius(row, 8, 0);
        lv_obj_set_style_border_width(row, 0, 0);
        lv_obj_set_style_pad_all(row, 0, 0);
        lv_obj_set_pos(row, 0, i * FM_ROW_H);

        char rowbuf[EOS_FS_NAME_MAX + 4];
        if (node->is_dir) {
            snprintf(rowbuf, sizeof(rowbuf), "%s/", node->name);
        } else {
            snprintf(rowbuf, sizeof(rowbuf), "%s", node->name);
        }

        lv_obj_t *lbl = lv_label_create(row);
        /* 文件名可能含中文:必须用 13px 档(jbm_13 → fallback han_sans_13,
         * 3850 字全字库)。10px 档(jbm_10 → han_sans_10)下汉字点阵被压成
         * 一团横线,看起来就是"下划线"。 */
        eos_label_set_font_size(lbl, EOS_FONT_SIZE_MICRO);
        lv_obj_set_style_text_color(lbl, node->is_dir ? lv_color_hex(_UI_ACCENT)
                                                      : lv_color_hex(_UI_TEXT), 0);
        lv_obj_set_style_text_opa(lbl, LV_OPA_COVER, 0);
        lv_obj_set_width(lbl, name_w);
        lv_obj_align(lbl, LV_ALIGN_LEFT_MID, 8 + depth * 12, 0);
        lv_label_set_long_mode(lbl, LV_LABEL_LONG_MODE_CLIP);
        lv_obj_set_style_text_align(lbl, LV_TEXT_ALIGN_LEFT, 0);
        lv_label_set_text(lbl, rowbuf);
        lv_obj_remove_flag(lbl, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_remove_flag(lbl, LV_OBJ_FLAG_SCROLLABLE);

        {
            /* 箭头是唯一可点热区:文件夹点箭头展开/收起,文件点箭头直接打开
             * (点行本身不反应)。文件夹展开时显示下箭头,其余显示右箭头。 */
            lv_obj_t *arrbtn = lv_button_create(row);
            lv_obj_remove_style_all(arrbtn);
            lv_obj_set_size(arrbtn, 34, FM_ROW_H);
            lv_obj_align(arrbtn, LV_ALIGN_RIGHT_MID, -2, 0);
            lv_obj_clear_flag(arrbtn, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_bg_opa(arrbtn, 0, 0);
            lv_obj_set_style_bg_opa(arrbtn, 60, LV_STATE_PRESSED);
            lv_obj_set_style_radius(arrbtn, 6, 0);
            lv_obj_add_event_cb(arrbtn, _fm_arrow_cb, LV_EVENT_CLICKED, node);
            lv_obj_t *arr = lv_label_create(arrbtn);
            lv_obj_set_style_text_font(arr, &EOS_FONT_ICON, 0);
            lv_obj_set_style_text_color(arr, lv_color_hex(_UI_DIM), 0);
            lv_label_set_text(arr, node->expanded ? RI_ARROW_DOWN_S_LINE
                                                  : RI_ARROW_RIGHT_S_LINE);
            lv_obj_center(arr);
        }

        lv_obj_add_event_cb(row, _fm_row_cb, LV_EVENT_CLICKED, node);
    }

    /* 恢复滚动位置,保持展开/收起前视口不变(超出新内容时 LVGL 自动 clamp) */
    if (scroll_y > 0)
        lv_obj_scroll_to_y(s_fm_list, scroll_y, LV_ANIM_OFF);
}

static void _fm_close(void)
{
    if (!s_fm_open) return;
    s_fm_open = false;

    if (s_fm_items) { eos_free(s_fm_items); s_fm_items = NULL; }
    s_fm_item_count = 0;
    if (s_fm_root) {
        _fm_children_free(s_fm_root);
        eos_free(s_fm_root);   /* root itself is a single malloc'd node */
        s_fm_root = NULL;
    }

    if (s_fm_mask) { lv_obj_delete(s_fm_mask); s_fm_mask = NULL; }
    s_fm_panel = NULL;
    s_fm_list  = NULL;
    s_fm_title = NULL;
}

/* 依次展开一个目录路径(含其父链,同步 IO 逐个展开)。目录已不存在时返回 false。 */
static bool _fm_expand_path(const char *path)
{
    if (!path || !path[0] || !s_fm_root) return false;
    if (strncmp(path, ALBUM_DIR, strlen(ALBUM_DIR)) != 0) return false;

    _fm_node_t *cur = s_fm_root;
    const char *p = path + strlen(ALBUM_DIR);
    char seg[EOS_FS_NAME_MAX];

    while (*p) {
        while (*p == '/') p++;
        if (!*p) break;
        size_t n = 0;
        while (*p && *p != '/' && n < sizeof(seg) - 1) seg[n++] = *p++;
        seg[n] = '\0';

        if (!cur->loaded) _fm_node_load(cur);
        cur->expanded = true;            /* 展开父目录才能继续向下找 */

        _fm_node_t *match = NULL;
        for (int i = 0; i < cur->child_count; i++) {
            if (cur->children[i].is_dir &&
                strcmp(cur->children[i].name, seg) == 0) {
                match = &cur->children[i];
                break;
            }
        }
        if (!match) return false;
        cur = match;
    }
    if (!cur->loaded) _fm_node_load(cur);
    cur->expanded = true;
    return true;
}

/* FM 打开时,依次展开历史记录的文件夹;目录已消失的记录移除 */
static void _fm_restore_expanded(void)
{
    if (!s_fm_root) return;
    for (int i = 0; i < s_fm_exp_count; ) {
        if (_fm_expand_path(s_fm_exp[i])) {
            i++;
        } else {
            _fm_exp_remove(s_fm_exp[i]);   /* 目录没了,清掉记录 */
        }
    }
}

/* Best-effort restore of the FM scroll position when it opens: walk the
 * anchor image path from the root, expand every directory on the way,
 * then scroll the flattened list so the anchor row is visible.  If the
 * anchor or any directory along the way no longer exists, give up. */
static void _fm_restore_position(void)
{
    if (!s_fm_root || s_fm_anchor[0] == '\0') return;
    if (strncmp(s_fm_anchor, ALBUM_DIR, strlen(ALBUM_DIR)) != 0) return;
    if (!_is_image_ext(_base(s_fm_anchor))) return;

    _fm_node_t *cur = s_fm_root;
    const char *p = s_fm_anchor + strlen(ALBUM_DIR);
    char seg[EOS_FS_NAME_MAX];
    bool changed = false;

    while (*p) {
        while (*p == '/') p++;          /* skip slashes */
        if (!*p) break;
        size_t n = 0;
        while (*p && *p != '/' && n < sizeof(seg) - 1) seg[n++] = *p++;
        seg[n] = '\0';
        if (!*p) break;                  /* last segment = the image file */

        if (!cur->loaded) _fm_node_load(cur);
        _fm_node_t *match = NULL;
        for (int i = 0; i < cur->child_count; i++) {
            if (cur->children[i].is_dir &&
                strcmp(cur->children[i].name, seg) == 0) {
                match = &cur->children[i];
                break;
            }
        }
        if (!match) break;               /* dir gone: keep what we expanded */
        match->expanded = true;
        changed = true;
        cur = match;
    }

    if (changed) _fm_rebuild();

    /* scroll so the anchor image row is visible */
    for (int i = 0; i < s_fm_item_count; i++) {
        if (s_fm_items[i].node &&
            strcmp(s_fm_items[i].node->path, s_fm_anchor) == 0) {
            lv_obj_scroll_to_y(s_fm_list, i * FM_ROW_H, LV_ANIM_OFF);
            break;
        }
    }
}

/* 点行右侧箭头:文件夹展开/收起,文件直接打开(不冒泡到行,点行本身不响应) */
static void _fm_arrow_cb(lv_event_t *e)
{
    _fm_node_t *node = (_fm_node_t *)lv_event_get_user_data(e);
    if (!node) return;
    lv_event_stop_bubbling(e);   /* 箭头热区消费点击,行不响应 */
    if (node->is_dir) {
        if (node->expanded) {
            node->expanded = false;
            _fm_children_free(node);
            _fm_exp_remove(node->path);   /* 收起:历史中含则删,不含不处理 */
        } else {
            if (!node->loaded) _fm_node_load(node);
            node->expanded = true;
            _fm_exp_add(node->path);      /* 展开:记录到历史,只留最新 3 个 */
        }
        _fm_rebuild();
    } else {
        /* 文件:点箭头单击直接打开,记住 anchor 下次 FM 打开滚动到它 */
        char path[EOS_FS_PATH_MAX];
        strncpy(path, node->path, sizeof(path) - 1);
        path[sizeof(path) - 1] = '\0';
        _write_fm_anchor(path);
        _fm_close();
        _open_image_path(path);
    }
}

static void _fm_row_cb(lv_event_t *e)
{
    _fm_node_t *node = (_fm_node_t *)lv_event_get_user_data(e);
    if (!node) return;
    /* 行本身不再响应点击:文件夹点右侧箭头展开/收起,文件点右侧箭头打开 */
}

static void _fm_close_cb(lv_event_t *e)
{
    (void)e;
    _fm_close();
}

static void _fm_open(void);

static void _fm_open_cb(lv_event_t *e)
{
    (void)e;
    _fm_open();
}

static void _fm_open(void)
{
    if (s_fm_open) return;
    s_fm_open = true;
    EOS_LOG_I("Album: fm open");

    /* mask: full-screen solid dark backdrop + tap-to-close */
    s_fm_mask = lv_obj_create(s_root);
    lv_obj_remove_style_all(s_fm_mask);
    lv_obj_set_size(s_fm_mask, 240, 240);
    lv_obj_set_pos(s_fm_mask, 0, 0);
    lv_obj_set_style_bg_color(s_fm_mask, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(s_fm_mask, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(s_fm_mask, 0, 0);
    lv_obj_clear_flag(s_fm_mask, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(s_fm_mask, _fm_close_cb, LV_EVENT_CLICKED, NULL);

    /* transparent container: the file tree renders directly on the solid
     * dark backdrop */
    s_fm_panel = lv_obj_create(s_fm_mask);
    lv_obj_remove_style_all(s_fm_panel);
    lv_obj_set_size(s_fm_panel, 212, 208);
    lv_obj_set_pos(s_fm_panel, 14, 24);
    lv_obj_set_style_bg_opa(s_fm_panel, LV_OPA_TRANSP, 0);
    lv_obj_set_style_radius(s_fm_panel, 0, 0);
    lv_obj_set_style_border_width(s_fm_panel, 0, 0);
    lv_obj_clear_flag(s_fm_panel, LV_OBJ_FLAG_SCROLLABLE);
    /* panel sits above the mask; no event bubbling to mask by default */

    /* header: path + close */
    s_fm_title = lv_label_create(s_fm_panel);
    eos_label_set_font_size(s_fm_title, EOS_FONT_SIZE_MICRO);
    lv_obj_set_style_text_color(s_fm_title, lv_color_hex(_UI_DIM), 0);
    lv_obj_set_size(s_fm_title, 140, 18);
    lv_obj_set_pos(s_fm_title, 14, 10);
    lv_label_set_long_mode(s_fm_title, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(s_fm_title, ALBUM_DIR);
    lv_obj_remove_flag(s_fm_title, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(s_fm_title, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *close = lv_button_create(s_fm_panel);
    lv_obj_remove_style_all(close);
    lv_obj_set_size(close, 26, 22);
    lv_obj_set_pos(close, 176, 8);
    lv_obj_set_style_bg_color(close, lv_color_hex(_UI_TEXT), 0);
    lv_obj_set_style_bg_opa(close, 18, 0);
    lv_obj_set_style_radius(close, 8, 0);
    lv_obj_add_event_cb(close, _fm_close_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t *cl = lv_label_create(close);
    lv_obj_set_style_text_font(cl, &EOS_FONT_ICON, 0);
    lv_obj_set_style_text_color(cl, lv_color_hex(_UI_TEXT), 0);
    lv_label_set_text(cl, RI_CLOSE_FILL);
    lv_obj_center(cl);
    lv_obj_remove_flag(cl, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(cl, LV_OBJ_FLAG_SCROLLABLE);

    /* list (5 rows of FM_ROW_H visible) */
    s_fm_list = lv_obj_create(s_fm_panel);
    lv_obj_remove_style_all(s_fm_list);
    lv_obj_set_size(s_fm_list, 200, 172);
    lv_obj_set_pos(s_fm_list, 6, 30);
    lv_obj_set_style_radius(s_fm_list, 10, 0);
    lv_obj_set_style_pad_all(s_fm_list, 0, 0);
    lv_obj_set_style_border_width(s_fm_list, 0, 0);
    lv_obj_add_flag(s_fm_list, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(s_fm_list, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_scroll_dir(s_fm_list, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(s_fm_list, LV_SCROLL_SNAP_NONE);
    lv_obj_set_style_bg_color(s_fm_list, lv_color_hex(_UI_DIM), LV_PART_SCROLLBAR);
    lv_obj_set_style_bg_opa(s_fm_list, LV_OPA_COVER, LV_PART_SCROLLBAR);
    lv_obj_set_style_radius(s_fm_list, 4, LV_PART_SCROLLBAR);

    /* root node */
    s_fm_root = (_fm_node_t *)eos_malloc_zeroed(sizeof(_fm_node_t));
    if (s_fm_root) {
        strncpy(s_fm_root->name, "album", sizeof(s_fm_root->name) - 1);
        strncpy(s_fm_root->path, ALBUM_DIR, sizeof(s_fm_root->path) - 1);
        s_fm_root->is_dir = true;
        s_fm_root->expanded = true;    /* show root level immediately */
        _fm_node_load(s_fm_root);      /* load root lazily now */
    } else {
        EOS_LOG_E("Album: root alloc FAIL size=%u", (unsigned)sizeof(_fm_node_t));
    }

    /* 依次展开上次展开过的文件夹(最多 3 个,记录在历史文件) */
    _fm_restore_expanded();

    _fm_rebuild();

    /* restore scroll position from the last FM browse (best effort) */
    _fm_restore_position();
}

/* ------------------------------------------------------------------ */
/* Events                                                             */
/* ------------------------------------------------------------------ */

static void _prev_cb(lv_event_t *e)
{
    (void)e;
    if (s_count <= 0) return;
    s_index = (s_index + s_count - 1) % s_count;
    _show_current();
}

static void _next_cb(lv_event_t *e)
{
    (void)e;
    if (s_count <= 0) return;
    s_index = (s_index + 1) % s_count;
    _show_current();
}

/* Remove the pre-encoded assets that travel with `img` (the thumbnail bin
 * and the whole 1:1 tile grid folder) so they never linger after delete. */
static void _delete_assets(const char *img)
{
    if (!img || !img[0]) return;
    char p[ALBUM_PATH_BUF];

    _thumb_path(img, p, sizeof(p));       /* <dir>/.thumb/<base>.bin */
    if (eos_storage_is_file(p)) eos_storage_file_remove(p);

    _tiles_dir(img, p, sizeof(p));        /* <dir>/.tiles/<base>/ */
    eos_dir_t d = eos_storage_dir_open(p);
    if (!d) return;
    char name[EOS_FS_NAME_MAX];
    while (eos_storage_dir_read(d, name, sizeof(name)) == EOS_OK) {
        if (name[0] == '\0' || name[0] == '.') continue;
        char full[ALBUM_PATH_BUF];
        snprintf(full, sizeof(full), "%s/%s", p, name);
        if (eos_storage_is_file(full)) eos_storage_file_remove(full);
    }
    eos_storage_dir_close(d);
}

static void _trash_cb(lv_event_t *e)
{
    (void)e;
    if (s_count <= 0) return;

    const char *path = s_paths[s_index];
    EOS_LOG_I("Album: delete %s", path);
    eos_storage_file_remove(path);
    _delete_assets(path);   /* also drop .thumb bin + .tiles grid */

    for (int i = s_index; i < s_count - 1; i++) {
        strcpy(s_paths[i], s_paths[i + 1]);
    }
    s_count--;
    if (s_count <= 0) {
        s_index = 0;
        _show_empty();
        return;
    }
    if (s_index >= s_count) s_index = s_count - 1;
    _show_current();
}

/* image touch gestures (single-point touch hardware):
 *  - double-tap (two press+release, small moves, < 300 ms apart)
 *                                        -> enter/exit 1:1 tile browse
 *  - drag (move while pressed, in 1:1)   -> pan the viewport
 * Only one touch point exists (CHSC6X), so no pinch.
 * A single tap never switches modes; only a double tap toggles, so a
 * swipe can never be mistaken for a zoom-out trigger. */
#define ALBUM_DOUBLE_TAP_MS 300
static int      s_press_x = 0, s_press_y = 0;  /* press origin (drag) */
static int      s_last_x  = 0, s_last_y  = 0;  /* last PRESSING sample */
static bool     s_dragging = false;
static uint32_t s_last_tap_t = 0;              /* tick of previous tap */

static void _img_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_indev_t *indev = lv_indev_active();
    if (!indev) return;
    lv_point_t p;
    lv_indev_get_point(indev, &p);

    if (code == LV_EVENT_PRESSED) {
        s_press_x = p.x;
        s_press_y = p.y;
        s_last_x  = p.x;
        s_last_y  = p.y;
        s_dragging = false;
    }
    else if (code == LV_EVENT_PRESSING) {
        /* per-event delta pans the viewport; TOTAL travel from the press
         * origin decides tap-vs-drag.  The old code compared only the last
         * per-event delta, so slow/fast swipes could stay under the 8 px
         * threshold forever and RELEASED then mistook a drag for a tap,
         * kicking the user back to the thumbnail. */
        int dx = p.x - s_last_x;
        int dy = p.y - s_last_y;
        s_last_x = p.x;
        s_last_y = p.y;
        if (!s_dragging) {
            int adx = p.x - s_press_x;
            int ady = p.y - s_press_y;
            if ((int)lv_sqrt32((uint32_t)(adx * adx + ady * ady)) > 8) {
                s_dragging = true;
            }
        }
        if (s_dragging && s_tile_mode && s_ts > 0) {
            /* content follows finger: viewport moves opposite */
            s_view_x -= dx;
            s_view_y -= dy;
            int mx = s_orig_w - ALBUM_VIEW;
            int my = s_orig_h - ALBUM_VIEW;
            if (mx < 0) mx = 0;
            if (my < 0) my = 0;
            if (s_view_x < 0) s_view_x = 0;
            if (s_view_x > mx) s_view_x = mx;
            if (s_view_y < 0) s_view_y = 0;
            if (s_view_y > my) s_view_y = my;
            _tile_refresh();
        }
    }
    else if (code == LV_EVENT_RELEASED) {
        if (!s_dragging && s_count > 0) {
            uint32_t now = lv_tick_get();
            if (s_last_tap_t && (now - s_last_tap_t) <= ALBUM_DOUBLE_TAP_MS) {
                /* second tap in the window -> toggle 1:1 browse */
                s_last_tap_t = 0;                /* consume the double tap */
                if (s_tile_mode) _tile_exit();
                else _tile_enter(p.x, p.y);
            } else {
                s_last_tap_t = now;              /* arm: wait for 2nd tap */
            }
        } else {
            s_last_tap_t = 0;                    /* a drag cancels tap */
        }
        s_dragging = false;
    }
}

/* ------------------------------------------------------------------ */
/* UI                                                                 */
/* ------------------------------------------------------------------ */

static lv_obj_t *_make_btn(lv_obj_t *parent, int w, int h, uint32_t bg,
                           lv_align_t align, int x, int y,
                           lv_event_cb_t cb, const char *icon)
{
    lv_obj_t *btn = lv_button_create(parent);
    lv_obj_remove_style_all(btn);
    lv_obj_set_size(btn, w, h);
    lv_obj_set_style_bg_color(btn, lv_color_hex(bg), 0);
    lv_obj_set_style_bg_opa(btn, LV_OPA_70, 0);
    lv_obj_set_style_radius(btn, 12, 0);
    lv_obj_set_style_border_width(btn, 0, 0);
    lv_obj_align(btn, align, x, y);
    lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, NULL);

    lv_obj_t *lbl = lv_label_create(btn);
    lv_obj_set_style_text_font(lbl, &EOS_FONT_ICON, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(_UI_TEXT), 0);
    lv_label_set_text(lbl, icon);
    lv_obj_center(lbl);
    return btn;
}

/* Rounded button in capsule grey with an image icon (bottom capsule bar). */
static lv_obj_t *_make_img_btn(lv_obj_t *parent, int w, int h, uint32_t bg,
                               lv_align_t align, int x, int y,
                               lv_event_cb_t cb, const lv_image_dsc_t *img)
{
    lv_obj_t *btn = lv_button_create(parent);
    lv_obj_remove_style_all(btn);
    lv_obj_set_size(btn, w, h);
    lv_obj_set_style_bg_color(btn, lv_color_hex(bg), 0);
    lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(btn, 12, 0);
    lv_obj_set_style_border_width(btn, 0, 0);
    lv_obj_align(btn, align, x, y);
    lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, NULL);

    lv_obj_t *icon = lv_image_create(btn);
    lv_image_set_src(icon, img);
    lv_obj_center(icon);
    return btn;
}

static void _build_ui(eos_activity_t *act)
{
    s_root = eos_activity_get_view(act);
    lv_obj_set_style_bg_color(s_root, lv_color_hex(_UI_BG), 0);
    eos_round_clip(s_root);

    /* scrolling file name */
    s_name = lv_label_create(s_root);
    lv_obj_set_width(s_name, ALBUM_NAME_W);
    lv_label_set_long_mode(s_name, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_obj_set_style_text_color(s_name, lv_color_hex(_UI_TEXT), 0);
    lv_obj_set_style_text_font(s_name, &lv_font_montserrat_14, 0);
    lv_obj_align(s_name, LV_ALIGN_TOP_MID, 0, 24);

    /* image (tap to zoom, drag to pan when zoomed in) */
    s_img = lv_image_create(s_root);
    lv_obj_center(s_img);
    lv_obj_add_flag(s_img, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(s_img, _img_event_cb, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(s_img, _img_event_cb, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(s_img, _img_event_cb, LV_EVENT_RELEASED, NULL);

    /* left / right arrows */
    s_prev_btn = _make_btn(s_root, 30, 56, _UI_BTN_BG, LV_ALIGN_LEFT_MID, 2, 0,
                           _prev_cb, RI_ARROW_LEFT_S_LINE);
    s_next_btn = _make_btn(s_root, 30, 56, _UI_BTN_BG, LV_ALIGN_RIGHT_MID, -2, 0,
                           _next_cb, RI_ARROW_RIGHT_S_LINE);

    /* bottom action capsule: delete + file manager, side by side, centred
     * above the bottom edge (buttons match the capsule, icon only). */
    s_capsule = lv_obj_create(s_root);
    lv_obj_remove_style_all(s_capsule);
    lv_obj_set_size(s_capsule, 112, 56);
    lv_obj_set_style_bg_color(s_capsule, lv_color_hex(_UI_CAPSULE), 0);
    lv_obj_set_style_bg_opa(s_capsule, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(s_capsule, 28, 0);   /* pill shape */
    lv_obj_set_style_border_width(s_capsule, 0, 0);
    lv_obj_align(s_capsule, LV_ALIGN_BOTTOM_MID, 0, -12);

    s_trash_btn = _make_img_btn(s_capsule, 44, 40, _UI_CAPSULE,
                                LV_ALIGN_LEFT_MID, 8, 0,
                                _trash_cb, &eos_icon_delete);
    s_fm_btn = _make_img_btn(s_capsule, 44, 40, _UI_CAPSULE,
                             LV_ALIGN_RIGHT_MID, -8, 0,
                             _fm_open_cb, &eos_icon_fm);

    /* counter */
    s_counter = lv_label_create(s_root);
    lv_obj_set_style_text_color(s_counter, lv_color_hex(_UI_DIM), 0);
    lv_obj_set_style_text_font(s_counter, &lv_font_montserrat_12, 0);
    lv_obj_align(s_counter, LV_ALIGN_BOTTOM_LEFT, 8, -16);

    /* message */
    s_msg = lv_label_create(s_root);
    lv_obj_set_style_text_color(s_msg, lv_color_hex(_UI_DIM), 0);
    lv_obj_set_style_text_font(s_msg, &lv_font_montserrat_14, 0);
    lv_obj_set_style_text_align(s_msg, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_width(s_msg, 180);
    lv_obj_center(s_msg);
}

/* ------------------------------------------------------------------ */
/* Lifecycle                                                          */
/* ------------------------------------------------------------------ */

/* 1:1 浏览状态下右滑是"拖图看细节"手势，不能被系统当成退出；
 * 缩略图态右滑仍按系统默认退出。 */
static bool _swipe_back_cb(eos_activity_t *self, lv_dir_t dir)
{
    (void)self;
    (void)dir;
    return s_tile_mode;
}

static void _on_enter(eos_activity_t *act)
{
    s_act = act;
    eos_activity_set_swipe_back_handler(act, _swipe_back_cb);
    _build_ui(act);

    /* resume last viewed image; otherwise open the file manager */
    char hist[EOS_FS_PATH_MAX];
    if (_read_history(hist, sizeof(hist)) && _is_image_ext(_base(hist))) {
        if (!_open_image_path(hist)) {
            _show_empty();
            _fm_open();
        }
    } else {
        _show_empty();
        _fm_open();
    }
}

static void _on_destroy(eos_activity_t *act)
{
    (void)act;
    if (s_fm_open) _fm_close();
    _tile_exit();      /* release tile PSRAM before app teardown */
    _free_pixels();
    if (s_paths) {
        eos_free(s_paths);
        s_paths = NULL;
    }
    s_count = 0;
    s_index = 0;
}

static const eos_activity_lifecycle_t s_lifecycle = {
    .on_enter   = _on_enter,
    .on_destroy = _on_destroy,
};

void eos_album_enter(void)
{
    EOS_LOG_I("Album: enter");
    eos_activity_t *act = eos_activity_create(&s_lifecycle);
    eos_activity_set_type(act, EOS_ACTIVITY_TYPE_APP);
    eos_activity_enter(act);
}
