/**
 * @file eos_texthub.c
 * @brief Texthub - native C text reader (.txt/.md) for /sdcard/texthub/
 *
 * Replaces the old JS app (apps/texthub) which crashed with
 * JERRY_FATAL_OUT_OF_MEMORY because it synchronously enumerated every file
 * under /sdcard/texthub/ into the fixed 512KB JerryScript heap.
 *
 * C version design:
 *   - Lazy File Manager (FM) overlay: only the directory being expanded is
 *     read (eos_storage_dir_open); children are freed when collapsed or when
 *     the FM closes (memory stays small, no full-tree scan).
 *   - Chunked reading: files <= 128KB load in one shot; larger files are
 *     read segment-by-segment (16KB, newline-aligned) on scroll end.
 *   - History: /sdcard/history/texthub/latest.txt stores the last opened
 *     file path (line 1), reading position permille (line 2) and FM anchor
 *     (line 3: last file opened from the FM, restores the FM scroll
 *     position); the last file is auto-opened on entry (FM shown when
 *     absent).
 *   - UI (240x240 round, Album style): floating filename on top, prev/next
 *     arrows, bottom action capsule (delete + FM), bottom-left indicator.
 *     The capsule and arrows hide while the text scrolls and return when
 *     scrolling stops. English only; CJK shown via jbm_13's han_sans_13
 *     fallback.
 *
 * UI layout (all inside the round clipping region):
 *   System statusbar: y0..24 (owned by the framework)
 *   Floating filename: top-mid (0,24), w132, circular marquee
 *   Prev/next arrows: 30x56 at left/right mid
 *   Text card: x14 y60 w212 h132, rounded, drag-to-scroll
 *   Action capsule: 112x56 pill at bottom-mid (0,-12): delete + FM icons
 *   Bottom: bottom-left (8,-16), "idx/total | seg x"
 */

#include "eos_texthub.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#include "eos_log.h"
#include "eos_config.h"
#include "eos_mem.h"
#include "eos_activity.h"
#include "eos_service_storage.h"
#include "eos_storage_paths.h"
#include "eos_font.h"
#include "eos_icon.h"
#include "ui/system/eos_round_clip.h"
#include "lvgl.h"

#define EOS_LOG_TAG "Texthub"

/* ------------------------------------------------------------------ */
/* Config                                                             */
/* ------------------------------------------------------------------ */

#define TH_DIR          "/sdcard/texthub"
#define TH_HIST_DIR     "/sdcard/history/texthub"
#define TH_HIST_FILE    "/sdcard/history/texthub/latest.txt"

#define TH_READ_ONCE_MAX   (128 * 1024)   /* files this size load at once  */
#define TH_SEG_BYTES       (16 * 1024)    /* chunk size for large files    */
#define TH_SEG_LINE_MAX    (4096)         /* guard against one giant line  */
#define TH_MAX_FILE_SIZE   (32 * 1024 * 1024) /* refuse anything bigger    */
#define TH_FM_EXP_MAX      3             /* remembered expanded FM dirs (newest 3) */

#define TH_FM_DEPTH_MAX    6              /* FM tree max recursion depth   */
#define TH_FM_MAX_CHILD    300            /* entries per expanded dir      */
#define TH_FM_MAX_VISIBLE  300            /* visible rows cap              */
#define TH_FM_ROW_H        24             /* compact row spacing (TINY 10px) */

#define TH_NAME_W          132            /* floating filename width      */

#define _UI_BG        0x12121A            /* background (Album style)     */
#define _UI_CARD      0xFFFFFF
#define _UI_CARD_OPA  8
#define _UI_TEXT      0xFFFFFF
#define _UI_DIM       0x8A8F98
#define _UI_ACCENT    0x6CB6FF            /* directories in the FM         */
#define _UI_BTN_BG    0x1E1E2E            /* arrow button background      */
#define _UI_CAPSULE   0x34343F            /* bottom action capsule        */
#define _UI_PANEL     0x1E1E2E

/* ------------------------------------------------------------------ */
/* Types                                                              */
/* ------------------------------------------------------------------ */

typedef struct th_node_t th_node_t;
struct th_node_t {
    char    name[EOS_FS_NAME_MAX];
    char    path[EOS_FS_PATH_MAX];
    bool    is_dir;
    bool    expanded;
    bool    loaded;
    int     depth;                       /* depth in the FM tree         */
    int     child_count;
    th_node_t *children;                 /* array of children (lazy)      */
};

typedef struct {
    th_node_t *node;
    int        depth;
} th_item_t;

/* ------------------------------------------------------------------ */
/* State                                                              */
/* ------------------------------------------------------------------ */

static eos_activity_t *s_act;
static lv_obj_t *s_root, *s_name, *s_card, *s_body, *s_bottom;
static lv_obj_t *s_prev_btn, *s_next_btn;              /* side arrows   */
static lv_obj_t *s_capsule, *s_trash_btn, *s_fm_btn;  /* capsule bar   */

/* generated by scripts/icon/webp2c.py (compiled into the firmware) */
extern const lv_image_dsc_t eos_icon_fm;
extern const lv_image_dsc_t eos_icon_delete;

/* current file */
static char     *s_cur_path;             /* full path or NULL            */
static char     *s_cur_dir;              /* parent dir or NULL           */
static int       s_cur_idx;              /* index inside same-dir list   */
static int       s_cur_total;
/* reading position (permille 0..10000) persisted to history on exit */
static uint32_t  s_cur_pos;              /* 0 = top, 10000 = end         */
static bool      s_restoring;            /* suppress scroll callbacks during restore */

/* text buffer */
static eos_file_t s_fp = EOS_FILE_INVALID;
static char      *s_text;                /* full text (small) or segment */
static uint32_t   s_size;
static bool       s_seg_mode;
static uint32_t   s_seg_start, s_seg_end, s_seg_idx;

/* file manager overlay */
static bool       s_fm_open;
static lv_obj_t  *s_fm_mask, *s_fm_panel, *s_fm_list, *s_fm_path;
static th_node_t *s_fm_root;
static th_item_t *s_fm_items;
static int        s_fm_item_count;
static char       s_fm_anchor[EOS_FS_PATH_MAX];   /* last file opened from FM
                                                   * (history line 3): the FM
                                                   * reopens scrolled to it */
/* FM 展开记录:上次 FM 打开时展开过的目录(最多 TH_FM_EXP_MAX 个,行尾最新) */
static char       s_fm_exp[TH_FM_EXP_MAX][EOS_FS_PATH_MAX];
static int        s_fm_exp_count;

/* ------------------------------------------------------------------ */
/* Helpers                                                            */
/* ------------------------------------------------------------------ */

static const char *_base(const char *path)
{
    const char *s = strrchr(path, '/');
    return s ? s + 1 : path;
}

static bool _is_text_ext(const char *name)
{
    const char *dot = strrchr(name, '.');
    if (!dot || dot[1] == '\0') return false;
    const char *e = dot + 1;
    return (strcasecmp(e, "txt") == 0) || (strcasecmp(e, "md") == 0);
}

static void _dir_of(const char *path, char *buf, size_t sz)
{
    const char *s = strrchr(path, '/');
    size_t len = s ? (size_t)(s - path) : 0;
    if (len >= sz) len = sz - 1;
    memcpy(buf, path, len);
    buf[len] = '\0';
    if (len == 0) strcpy(buf, "/");
}

static int _cmp_name(const void *a, const void *b)
{
    const char *const *pa = (const char *const *)a;
    const char *const *pb = (const char *const *)b;
    return strcasecmp(*pa, *pb);
}

/* ------------------------------------------------------------------ */
/* Text loading                                                       */
/* ------------------------------------------------------------------ */

static void _free_text(void)
{
    if (s_fp != EOS_FILE_INVALID) {
        eos_storage_file_close(s_fp);
        s_fp = EOS_FILE_INVALID;
    }
    if (s_text) {
        eos_free(s_text);
        s_text = NULL;
    }
    s_seg_mode = false;
    s_seg_start = s_seg_end = s_seg_idx = 0;
}

/* Read one segment (newline-aligned) starting at s_seg_end (or 0 for seg 0)
 * into s_text, advancing s_seg_start / s_seg_end. */
static bool _seg_load(uint32_t idx)
{
    if (s_fp == EOS_FILE_INVALID) return false;

    uint32_t start = (idx == 0) ? 0 : s_seg_end;
    if (start >= s_size) return false;

    if (eos_storage_file_seek(s_fp, start) != EOS_OK) return false;

    char stack_buf[TH_SEG_BYTES];
    ssize_t rd = eos_storage_file_read(s_fp, stack_buf, TH_SEG_BYTES);
    if (rd <= 0) return false;
    uint32_t len = (uint32_t)rd;

    /* keep last whole line unless we reached EOF */
    if (start + len < s_size) {
        int32_t i = (int32_t)len - 1;
        while (i >= 0 && stack_buf[i] != '\n') i--;
        if (i >= 0) {
            len = (uint32_t)i + 1;               /* keep the '\n' */
        } else if (len > TH_SEG_LINE_MAX) {
            len = TH_SEG_LINE_MAX;               /* one giant line: clamp */
        }
        if (len == 0) return false;              /* nothing to show yet  */
    }

    char *txt = (char *)eos_malloc(len + 1);
    if (!txt) return false;
    memcpy(txt, stack_buf, len);
    txt[len] = '\0';

    if (s_text) eos_free(s_text);
    s_text = txt;
    s_seg_idx    = idx;
    s_seg_start  = start;
    s_seg_end    = start + len;
    return true;
}

static void _update_bar(void)
{
    /* filename (marquee handled by LVGL SCROLL_CIRCULAR) */
    if (s_cur_path) {
        lv_label_set_text(s_name, _base(s_cur_path));
    } else {
        lv_label_set_text(s_name, "Texthub");
    }

    /* bottom indicator */
    char buf[40];
    if (s_cur_total > 0) {
        if (s_seg_mode) {
            snprintf(buf, sizeof(buf), "%d/%d | seg %u",
                     s_cur_idx + 1, s_cur_total, (unsigned)(s_seg_idx + 1));
        } else {
            snprintf(buf, sizeof(buf), "%d/%d", s_cur_idx + 1, s_cur_total);
        }
    } else {
        strcpy(buf, "");
    }
    lv_label_set_text(s_bottom, buf);
}

static void _seg_next(void)
{
    if (s_seg_end >= s_size) return;
    uint32_t next = s_seg_idx + 1;
    if (_seg_load(next)) {
        lv_label_set_text(s_body, s_text);
        lv_obj_update_layout(s_card);
        lv_obj_scroll_to_y(s_card, 0, LV_ANIM_OFF);
        _update_bar();
    }
}

static void _seg_prev(void)
{
    if (s_seg_idx == 0) return;
    if (_seg_load(s_seg_idx - 1)) {
        lv_label_set_text(s_body, s_text);
        lv_obj_update_layout(s_card);
        lv_obj_scroll_to_y(s_card, LV_COORD_MAX, LV_ANIM_OFF);
        _update_bar();
    }
}

/* Update s_cur_pos (permille 0..10000) from the current scroll state. */
static void _update_cur_pos(void)
{
    if (!s_cur_path || s_size == 0) { s_cur_pos = 0; return; }

    int32_t sy = lv_obj_get_scroll_y(s_card);
    int32_t max_y = sy + lv_obj_get_scroll_bottom(s_card);
    if (max_y < 0) max_y = 0;

    if (!s_seg_mode) {
        s_cur_pos = (max_y > 0) ? (uint32_t)((uint64_t)sy * 10000 / (uint32_t)max_y) : 0;
    } else {
        /* position in file = seg_start + ratio inside the segment */
        uint32_t seg_len = s_seg_end - s_seg_start;
        uint32_t in_seg  = (max_y > 0)
            ? (uint32_t)((uint64_t)sy * seg_len / (uint32_t)max_y)
            : 0;
        s_cur_pos = (uint32_t)(((uint64_t)(s_seg_start + in_seg) * 10000) / s_size);
    }
    if (s_cur_pos > 10000) s_cur_pos = 10000;
}

/* Load a segment starting at an arbitrary byte offset (history restore).
 * Displayed segment number is approximated by start / TH_SEG_BYTES. */
static bool _seg_load_at(uint32_t start)
{
    if (s_fp == EOS_FILE_INVALID) return false;
    if (start >= s_size) return false;
    if (eos_storage_file_seek(s_fp, start) != EOS_OK) return false;

    char stack_buf[TH_SEG_BYTES];
    ssize_t rd = eos_storage_file_read(s_fp, stack_buf, TH_SEG_BYTES);
    if (rd <= 0) return false;
    uint32_t len = (uint32_t)rd;

    if (start + len < s_size) {
        int32_t i = (int32_t)len - 1;
        while (i >= 0 && stack_buf[i] != '\n') i--;
        if (i >= 0) {
            len = (uint32_t)i + 1;
        } else if (len > TH_SEG_LINE_MAX) {
            len = TH_SEG_LINE_MAX;
        }
        if (len == 0) return false;
    }

    char *txt = (char *)eos_malloc(len + 1);
    if (!txt) return false;
    memcpy(txt, stack_buf, len);
    txt[len] = '\0';

    if (s_text) eos_free(s_text);
    s_text = txt;
    s_seg_idx    = start / TH_SEG_BYTES;  /* approximate, display only */
    s_seg_start  = start;
    s_seg_end    = start + len;
    return true;
}

/* Restore reading position (permille 0..10000) right after _open_path. */
static void _restore_pos(uint32_t pos)
{
    if (!s_card || !s_cur_path || pos == 0 || pos > 10000) return;

    s_restoring = true;   /* suppress SCROLL_END handler during restore */
    if (!s_seg_mode) {
        int32_t max_y = lv_obj_get_scroll_y(s_card) + lv_obj_get_scroll_bottom(s_card);
        if (max_y > 0) {
            lv_obj_scroll_to_y(s_card, (int32_t)((uint64_t)max_y * pos / 10000), LV_ANIM_OFF);
        }
    } else {
        /* resume from a byte offset; segment granularity is acceptable */
        uint32_t byte = (uint32_t)((uint64_t)s_size * pos / 10000);
        if (_seg_load_at(byte)) {
            lv_label_set_text(s_body, s_text);
            lv_obj_update_layout(s_card);
            lv_obj_scroll_to_y(s_card, 0, LV_ANIM_OFF);
            _update_bar();
        }
    }
    s_restoring = false;
    _update_cur_pos();
}

/* ------------------------------------------------------------------ */
/* Same-directory text file listing (for idx/total and [>] next)      */
/* ------------------------------------------------------------------ */

/* Returns an eos_malloc'd array of eos_strdup'd names (sorted), or NULL. */
static char **_scan_text_names(const char *dir, int *out_count, const char *cur_path, int *out_idx)
{
    *out_count = 0;
    if (out_idx) *out_idx = -1;

    eos_dir_t d = eos_storage_dir_open(dir);
    if (!d) return NULL;

    char **names = NULL;
    int cap = 0, cnt = 0;
    char name[EOS_FS_NAME_MAX];

    while (eos_storage_dir_read(d, name, sizeof(name)) == EOS_OK) {
        if (name[0] == '\0' || name[0] == '.' || !_is_text_ext(name)) continue;
        if (cnt >= TH_FM_MAX_CHILD) break;
        if (cnt >= cap) {
            int ncap = cap ? cap * 2 : 16;
            char **nn = (char **)eos_realloc(names, (size_t)ncap * sizeof(char *));
            if (!nn) break;
            names = nn;
            cap = ncap;
        }
        names[cnt++] = eos_strdup(name);
    }
    eos_storage_dir_close(d);

    if (cnt == 0) {
        eos_free(names);
        return NULL;
    }
    qsort(names, cnt, sizeof(char *), _cmp_name);

    if (out_idx && cur_path) {
        const char *b = _base(cur_path);
        for (int i = 0; i < cnt; i++) {
            if (strcmp(names[i], b) == 0) { *out_idx = i; break; }
        }
    }
    *out_count = cnt;
    return names;
}

static void _free_names(char **names, int count)
{
    for (int i = 0; i < count; i++) eos_free(names[i]);
    eos_free(names);
}

/* ------------------------------------------------------------------ */
/* Open a file (full path)                                            */
/* ------------------------------------------------------------------ */

static void _show_centered_msg(const char *txt)
{
    if (!s_body) return;
    lv_label_set_text(s_body, txt);
    lv_obj_update_layout(s_card);
    lv_obj_scroll_to_y(s_card, 0, LV_ANIM_OFF);
}

/* Persist last file + reading position (permille 0..10000) + FM anchor +
 * FM expanded dirs. Format: "<path>\n<pos>\n<fm_anchor>\n<exp>\n"; a bare-path
 * line is the legacy format (pos=0); missing line 3 means "no FM position to
 * restore"; line 4 is "p1|p2|p3" (newest last, up to TH_FM_EXP_MAX). */
/* 序列化并写入历史文件(path 可为 NULL,此时其余行留空)。
 * Format: "<path>\n<pos>\n<fm_anchor>\n<exp>\n",exp 为 "p1|p2|p3"
 * (最新在行尾,最多 TH_FM_EXP_MAX 个)。 */
static void _fm_hist_write(const char *path, uint32_t pos)
{
    eos_storage_mkdir_recursive(TH_HIST_DIR);
    char buf[EOS_FS_PATH_MAX * 6 + 32];
    int n = snprintf(buf, sizeof(buf), "%s\n%u\n%s\n",
                     path ? path : "", (unsigned)pos, s_fm_anchor);
    /* line 4: 最近展开的文件夹(最多 3 个,| 分隔,行尾最新) */
    for (int i = 0; i < s_fm_exp_count && n > 0 && n < (int)sizeof(buf); i++) {
        n += snprintf(buf + n, sizeof(buf) - (size_t)n, "%s%s",
                      i ? "|" : "", s_fm_exp[i]);
    }
    if (n < 0) n = 0;
    if ((size_t)n > sizeof(buf)) n = (int)sizeof(buf);
    eos_storage_write_file(TH_HIST_FILE, buf, (size_t)n);
}

static void _write_history(const char *path, uint32_t pos)
{
    if (!path) return;
    _fm_hist_write(path, pos);
}

/* 解析历史中的展开记录行:"p1|p2|p3"(行尾最新),只取最新 TH_FM_EXP_MAX 个 */
static void _fm_exp_parse(const char *line)
{
    s_fm_exp_count = 0;
    if (!line || !line[0]) return;
    const char *tok = line;
    while (tok && *tok && s_fm_exp_count < TH_FM_EXP_MAX) {
        const char *sep = strchr(tok, '|');
        size_t len = sep ? (size_t)(sep - tok) : strlen(tok);
        if (len > 0 && len < EOS_FS_PATH_MAX &&
            strncmp(tok, TH_DIR, strlen(TH_DIR)) == 0) {
            memcpy(s_fm_exp[s_fm_exp_count], tok, len);
            s_fm_exp[s_fm_exp_count][len] = '\0';
            s_fm_exp_count++;
        }
        if (!sep) break;
        tok = sep + 1;
    }
}

/* 展开一个目录:已存在则移到末尾(最新);超过 TH_FM_EXP_MAX 个则丢弃最旧 */
static void _fm_exp_add(const char *path)
{
    if (!path || !path[0]) return;
    for (int i = 0; i < s_fm_exp_count; i++) {
        if (strcmp(s_fm_exp[i], path) == 0) {
            if (i != s_fm_exp_count - 1) {
                memmove(&s_fm_exp[i], &s_fm_exp[i + 1],
                        (size_t)(s_fm_exp_count - 1 - i) * sizeof(s_fm_exp[0]));
                s_fm_exp_count--;
                strncpy(s_fm_exp[s_fm_exp_count], path,
                        sizeof(s_fm_exp[0]) - 1);
                s_fm_exp[s_fm_exp_count][sizeof(s_fm_exp[0]) - 1] = '\0';
                s_fm_exp_count++;
            }
            _fm_hist_write(s_cur_path, s_cur_pos);
            return;
        }
    }
    if (s_fm_exp_count >= TH_FM_EXP_MAX) {
        memmove(&s_fm_exp[0], &s_fm_exp[1],
                (size_t)(s_fm_exp_count - 1) * sizeof(s_fm_exp[0]));
        s_fm_exp_count--;
    }
    strncpy(s_fm_exp[s_fm_exp_count], path, sizeof(s_fm_exp[0]) - 1);
    s_fm_exp[s_fm_exp_count][sizeof(s_fm_exp[0]) - 1] = '\0';
    s_fm_exp_count++;
    _fm_hist_write(s_cur_path, s_cur_pos);
}

/* 收起一个目录:历史中包含才删除,否则不处理 */
static void _fm_exp_remove(const char *path)
{
    if (!path || !path[0]) return;
    for (int i = 0; i < s_fm_exp_count; i++) {
        if (strcmp(s_fm_exp[i], path) == 0) {
            memmove(&s_fm_exp[i], &s_fm_exp[i + 1],
                    (size_t)(s_fm_exp_count - 1 - i) * sizeof(s_fm_exp[0]));
            s_fm_exp_count--;
            _fm_hist_write(s_cur_path, s_cur_pos);
            return;
        }
    }
}

static bool _open_path(const char *path)
{
    if (!path || !_is_text_ext(path)) return false;

    eos_file_t fp = eos_storage_file_open_read(path);
    if (fp == EOS_FILE_INVALID) {
        EOS_LOG_W("Texthub: open fail %s", path);
        _show_centered_msg("OPEN FAIL");
        return false;
    }

    uint32_t size = 0;
    if (eos_storage_file_size(fp, &size) != EOS_OK) {
        eos_storage_file_close(fp);
        _show_centered_msg("SIZE FAIL");
        return false;
    }
    if (size > TH_MAX_FILE_SIZE) {
        eos_storage_file_close(fp);
        _show_centered_msg("FILE TOO BIG");
        return false;
    }

    /* release previous file */
    _free_text();
    if (s_cur_path) { eos_free(s_cur_path); s_cur_path = NULL; }
    if (s_cur_dir)  { eos_free(s_cur_dir);  s_cur_dir  = NULL; }

    s_fp  = fp;
    s_size = size;

    if (size <= TH_READ_ONCE_MAX) {
        s_seg_mode = false;
        char *txt = (char *)eos_malloc(size + 1);
        if (!txt) {
            _free_text();
            _show_centered_msg("NO MEM");
            return false;
        }
        ssize_t rd = eos_storage_file_read(fp, txt, size);
        if (rd < 0) rd = 0;
        txt[rd] = '\0';
        s_text = txt;
    } else {
        s_seg_mode = true;
        if (!_seg_load(0)) {
            _free_text();
            _show_centered_msg("READ FAIL");
            return false;
        }
    }

    s_cur_path = eos_strdup(path);
    char dirbuf[EOS_FS_PATH_MAX];
    _dir_of(path, dirbuf, sizeof(dirbuf));
    s_cur_dir = eos_strdup(dirbuf);

    /* index / total within the same directory */
    int count = 0, idx = -1;
    char **names = _scan_text_names(s_cur_dir, &count, path, &idx);
    _free_names(names, count);
    s_cur_idx   = (idx >= 0) ? idx : 0;
    s_cur_total = count;

    /* render */
    lv_label_set_text(s_body, s_text);
    lv_obj_update_layout(s_card);
    lv_obj_scroll_to_y(s_card, 0, LV_ANIM_OFF);
    _update_bar();

    /* a fresh file always starts at the top */
    s_cur_pos = 0;
    _write_history(path, s_cur_pos);
    EOS_LOG_I("Texthub: opened %s (%u bytes%s)", path, size,
              s_seg_mode ? ", seg-mode" : "");
    return true;
}

/* [>] next file in the same directory */
static void _next_file(void)
{
    if (!s_cur_path || !s_cur_dir) return;

    int count = 0, idx = -1;
    char **names = _scan_text_names(s_cur_dir, &count, s_cur_path, &idx);
    if (!names || idx < 0 || idx >= count - 1) {
        _free_names(names, count);
        return;
    }
    char next_path[EOS_FS_PATH_MAX];
    snprintf(next_path, sizeof(next_path), "%s/%s", s_cur_dir, names[idx + 1]);
    _free_names(names, count);

    _open_path(next_path);
}

/* [<] previous file in the same directory */
static void _prev_file(void)
{
    if (!s_cur_path || !s_cur_dir) return;

    int count = 0, idx = -1;
    char **names = _scan_text_names(s_cur_dir, &count, s_cur_path, &idx);
    if (!names || idx <= 0) {
        _free_names(names, count);
        return;
    }
    char prev_path[EOS_FS_PATH_MAX];
    snprintf(prev_path, sizeof(prev_path), "%s/%s", s_cur_dir, names[idx - 1]);
    _free_names(names, count);

    _open_path(prev_path);
}

/* Trash can: delete the current file, then open the next one in the same
 * directory (or the first, or show an empty state). */
static void _trash_cb(lv_event_t *e)
{
    (void)e;
    if (!s_cur_path) return;
    EOS_LOG_I("Texthub: delete %s", s_cur_path);

    char dirbuf[EOS_FS_PATH_MAX];
    strncpy(dirbuf, s_cur_dir ? s_cur_dir : TH_DIR, sizeof(dirbuf) - 1);
    dirbuf[sizeof(dirbuf) - 1] = '\0';
    char cur[EOS_FS_PATH_MAX];
    strncpy(cur, s_cur_path, sizeof(cur) - 1);
    cur[sizeof(cur) - 1] = '\0';

    eos_storage_file_remove(s_cur_path);

    /* if the FM anchor points at the deleted file, drop it */
    if (s_fm_anchor[0] && strcmp(s_fm_anchor, cur) == 0) {
        s_fm_anchor[0] = '\0';
    }

    /* if history points at the deleted file, drop the record */
    if (eos_storage_is_file(TH_HIST_FILE)) {
        char *last = eos_storage_read_file(TH_HIST_FILE);
        if (last) {
            size_t cl = strlen(cur);
            if (strncmp(last, cur, cl) == 0 &&
                (last[cl] == '\0' || last[cl] == '\n')) {
                eos_storage_file_remove(TH_HIST_FILE);
            }
            eos_free(last);
        }
    }

    /* release current file */
    _free_text();
    eos_free(s_cur_path); s_cur_path = NULL;
    eos_free(s_cur_dir);  s_cur_dir  = NULL;
    s_cur_idx = s_cur_total = 0;
    s_cur_pos = 0;

    /* reopen the next remaining file, or the first, or empty state */
    int count = 0, idx = -1;
    char **names = _scan_text_names(dirbuf, &count, cur, &idx);
    int target = -1;
    if (names && count > 0) {
        target = (idx >= 0 && idx + 1 < count) ? idx + 1 : 0;
    }
    if (target >= 0) {
        char next_path[EOS_FS_PATH_MAX];
        snprintf(next_path, sizeof(next_path), "%s/%s", dirbuf, names[target]);
        _free_names(names, count);
        _open_path(next_path);
    } else {
        _free_names(names, count);
        _show_centered_msg("NO FILES\nTap FM to browse");
        lv_label_set_text(s_name, "Texthub");
        lv_label_set_text(s_bottom, "");
    }
}

/* ------------------------------------------------------------------ */
/* File Manager overlay (lazy tree)                                   */
/* ------------------------------------------------------------------ */

/* Free all descendants of n (recursively freeing each children array), but
 * NOT n itself. n->children is ONE malloc'd array of th_node_t structs; the
 * elements are not individually allocated, they are freed with the array. */
static void _fm_children_free(th_node_t *n)
{
    if (!n) return;
    if (n->children) {
        for (int i = 0; i < n->child_count; i++) {
            _fm_children_free(&n->children[i]);
        }
        eos_free(n->children);
        n->children = NULL;
    }
    n->child_count = 0;
    n->loaded = false;
    n->expanded = false;
}

static void _fm_node_unload(th_node_t *n)
{
    if (!n) return;
    _fm_children_free(n);   /* free the subtree, keep n itself */
}

/* Lazy load: read one directory into an array of children nodes. */
static bool _fm_node_load(th_node_t *n)
{
    if (n->loaded) return true;
    if (n->depth >= TH_FM_DEPTH_MAX) { n->loaded = true; return false; }

    /* pass 1: count entries */
    eos_dir_t d = eos_storage_dir_open(n->path);
    if (!d) {
        n->loaded = true;
        EOS_LOG_W("Texthub: opendir FAIL %s", n->path);
        return false;
    }
    int cnt = 0;
    char name[EOS_FS_NAME_MAX];
    while (eos_storage_dir_read(d, name, sizeof(name)) == EOS_OK) {
        if (name[0] == '\0' || name[0] == '.') continue;
        if (++cnt > TH_FM_MAX_CHILD) { cnt = TH_FM_MAX_CHILD; break; }
    }
    eos_storage_dir_close(d);
    EOS_LOG_I("Texthub: dir %s raw=%d", n->path, cnt);

    if (cnt == 0) { n->loaded = true; return false; }

    th_node_t *arr = (th_node_t *)eos_malloc_zeroed((size_t)cnt * sizeof(th_node_t));
    if (!arr) { n->loaded = true; return false; }

    /* pass 2: fill */
    d = eos_storage_dir_open(n->path);
    if (!d) { eos_free(arr); n->loaded = true; return false; }
    int i = 0;
    while (i < cnt && eos_storage_dir_read(d, name, sizeof(name)) == EOS_OK) {
        if (name[0] == '\0' || name[0] == '.') continue;
        char full[EOS_FS_PATH_MAX];
        size_t dl = strlen(n->path), nl = strlen(name);
        if (dl + 1 + nl + 1 > sizeof(full)) continue;
        memcpy(full, n->path, dl);
        full[dl] = '/';
        strcpy(full + dl + 1, name);

        bool is_dir = eos_storage_is_dir(full);
        if (!is_dir && !_is_text_ext(name)) continue; /* only text files */

        th_node_t *c = &arr[i];
        strncpy(c->name, name, sizeof(c->name) - 1);
        c->name[sizeof(c->name) - 1] = '\0';
        strncpy(c->path, full, sizeof(c->path) - 1);
        c->path[sizeof(c->path) - 1] = '\0';
        c->is_dir = is_dir;
        c->depth  = n->depth + 1;
        i++;
        if (i >= TH_FM_MAX_CHILD) break;
    }
    eos_storage_dir_close(d);

    n->children = arr;
    n->child_count = i;
    n->loaded = true;
    EOS_LOG_I("Texthub: dir %s children=%d", n->path, i);
    return i > 0;
}

static void _fm_build_items(th_node_t *n, int depth, int *cnt)
{
    if (*cnt >= TH_FM_MAX_VISIBLE) return;
    if (!n) return;
    s_fm_items[*cnt].node = n;
    s_fm_items[*cnt].depth = depth;
    (*cnt)++;

    /* only directories recurse (files are leaves: click opens them) */
    if (n->is_dir && n->expanded && n->children) {
        for (int i = 0; i < n->child_count && *cnt < TH_FM_MAX_VISIBLE; i++) {
            _fm_build_items(&n->children[i], depth + 1, cnt);
        }
    }
}

static void _fm_row_cb(lv_event_t *e);  /* fwd decl */
static void _fm_arrow_cb(lv_event_t *e);

static void _fm_rebuild(void)
{
    if (!s_fm_open || !s_fm_list) {
        EOS_LOG_W("Texthub: rebuild skip open=%d list=%p", s_fm_open, (void *)s_fm_list);
        return;
    }

    /* 保存滚动位置:clean 后内容高度归零,LVGL 会把 scroll 清零导致
     * 展开/收起后跳回列表顶部 */
    int32_t scroll_y = lv_obj_get_scroll_y(s_fm_list);

    /* clear old rows */
    lv_obj_clean(s_fm_list);

    if (!s_fm_root) {
        EOS_LOG_E("Texthub: rebuild root NULL");
        return;
    }
    if (!s_fm_root->loaded) _fm_node_load(s_fm_root);

    if (!s_fm_items) {
        s_fm_items = (th_item_t *)eos_malloc(TH_FM_MAX_VISIBLE * sizeof(th_item_t));
        if (!s_fm_items) {
            EOS_LOG_E("Texthub: items alloc FAIL size=%u",
                      (unsigned)(TH_FM_MAX_VISIBLE * sizeof(th_item_t)));
            return;
        }
        EOS_LOG_I("Texthub: items alloc OK");
    }
    int cnt = 0;
    _fm_build_items(s_fm_root, 0, &cnt);
    s_fm_item_count = cnt;
    EOS_LOG_I("Texthub: rebuild items=%d", cnt);

    for (int i = 0; i < cnt; i++) {
        th_node_t *node = s_fm_items[i].node;
        int depth = s_fm_items[i].depth;

        lv_obj_t *row = lv_button_create(s_fm_list);
        lv_obj_remove_style_all(row);
        /* NOTE: use constant width, NOT lv_obj_get_width(s_fm_list) -- right
         * after creation the list has not been laid out yet and get_width
         * returns 0, which makes the row width negative and it never draws. */
        lv_obj_set_size(row, 196, TH_FM_ROW_H);
        /* rows must not be scroll targets or they swallow the drag gesture
         * and the parent list can never scroll */
        lv_obj_clear_flag(row, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_color(row, lv_color_hex(_UI_TEXT), 0);
        lv_obj_set_style_bg_opa(row, i % 2 ? 12 : 0, 0);   /* faint zebra */
        lv_obj_set_style_radius(row, 8, 0);
        lv_obj_set_style_border_width(row, 0, 0);
        lv_obj_set_style_pad_all(row, 0, 0);
        lv_obj_set_pos(row, 2, i * TH_FM_ROW_H);

        char rowbuf[EOS_FS_NAME_MAX + 4];
        if (node->is_dir) {
            snprintf(rowbuf, sizeof(rowbuf), "%s/", node->name);
        } else {
            snprintf(rowbuf, sizeof(rowbuf), "%s", node->name);
        }

        lv_obj_t *lbl = lv_label_create(row);
        eos_label_set_font_size(lbl, EOS_FONT_SIZE_TINY);
        lv_obj_set_style_text_color(lbl, node->is_dir ? lv_color_hex(_UI_ACCENT)
                                                      : lv_color_hex(_UI_TEXT), 0);
        lv_obj_set_style_text_opa(lbl, LV_OPA_COVER, 0);
        lv_obj_set_width(lbl, 148);
        lv_obj_align(lbl, LV_ALIGN_LEFT_MID, 8 + depth * 10, 0);
        lv_label_set_long_mode(lbl, LV_LABEL_LONG_MODE_CLIP);
        lv_obj_set_style_text_align(lbl, LV_TEXT_ALIGN_LEFT, 0);
        lv_label_set_text(lbl, rowbuf);
        lv_obj_remove_flag(lbl, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_remove_flag(lbl, LV_OBJ_FLAG_SCROLLABLE);

        {
            /* 箭头是唯一可点热区:文件夹点箭头展开/收起,文件点箭头直接打开
             * (点行本身不反应)。文件夹展开时显示下箭头,其余显示右箭头。 */
            lv_obj_t *arrbtn = lv_button_create(row);
            lv_obj_remove_style_all(arrbtn);
            lv_obj_set_size(arrbtn, 34, TH_FM_ROW_H);
            lv_obj_align(arrbtn, LV_ALIGN_RIGHT_MID, -2, 0);
            lv_obj_clear_flag(arrbtn, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_bg_opa(arrbtn, 0, 0);
            lv_obj_set_style_bg_opa(arrbtn, 60, LV_STATE_PRESSED);
            lv_obj_set_style_radius(arrbtn, 6, 0);
            lv_obj_add_event_cb(arrbtn, _fm_arrow_cb, LV_EVENT_CLICKED, node);
            lv_obj_t *arr = lv_label_create(arrbtn);
            lv_obj_set_style_text_font(arr, &EOS_FONT_ICON, 0);
            lv_obj_set_style_text_color(arr, lv_color_hex(_UI_DIM), 0);
            lv_label_set_text(arr, node->expanded ? RI_ARROW_DOWN_S_LINE
                                                  : RI_ARROW_RIGHT_S_LINE);
            lv_obj_center(arr);
        }

        lv_obj_add_event_cb(row, _fm_row_cb, LV_EVENT_CLICKED, node);
    }
    EOS_LOG_I("Texthub: rows rendered=%d", cnt);

    /* 恢复滚动位置,保持展开/收起前视口不变(超出新内容时 LVGL 自动 clamp) */
    if (scroll_y > 0)
        lv_obj_scroll_to_y(s_fm_list, scroll_y, LV_ANIM_OFF);
}

static void _fm_close(void)
{
    if (!s_fm_open) return;
    s_fm_open = false;

    if (s_fm_items) { eos_free(s_fm_items); s_fm_items = NULL; }
    s_fm_item_count = 0;
    if (s_fm_root) {
        _fm_children_free(s_fm_root);
        eos_free(s_fm_root);   /* root itself is a single malloc'd node */
        s_fm_root = NULL;
    }

    if (s_fm_mask) { lv_obj_delete(s_fm_mask); s_fm_mask = NULL; }
    s_fm_panel = NULL;
    s_fm_list  = NULL;
    s_fm_path  = NULL;
}

/* 点行右侧箭头:文件夹展开/收起,文件直接打开(不冒泡到行,点行本身不响应) */
static void _fm_arrow_cb(lv_event_t *e)
{
    th_node_t *node = (th_node_t *)lv_event_get_user_data(e);
    if (!node) return;
    lv_event_stop_bubbling(e);   /* 箭头热区消费点击,行不响应 */
    if (node->is_dir) {
        if (node->expanded) {
            node->expanded = false;
            _fm_node_unload(node);
            _fm_exp_remove(node->path);   /* 收起:历史中含则删,不含不处理 */
        } else {
            if (!node->loaded) _fm_node_load(node);
            node->expanded = true;
            _fm_exp_add(node->path);      /* 展开:记录到历史,只留最新 3 个 */
        }
        _fm_rebuild();
    } else {
        /* 文件:点箭头单击直接打开,记住 anchor 下次 FM 打开滚动到它 */
        char path[EOS_FS_PATH_MAX];
        strncpy(path, node->path, sizeof(path) - 1);
        path[sizeof(path) - 1] = '\0';
        strncpy(s_fm_anchor, path, sizeof(s_fm_anchor) - 1);
        s_fm_anchor[sizeof(s_fm_anchor) - 1] = '\0';
        _fm_close();
        _open_path(path);
    }
}

static void _fm_row_cb(lv_event_t *e)
{
    th_node_t *node = (th_node_t *)lv_event_get_user_data(e);
    if (!node) return;
    /* 行本身不再响应点击:文件夹点右侧箭头展开/收起,文件点右侧箭头打开 */
}

static void _fm_close_cb(lv_event_t *e)
{
    (void)e;
    _fm_close();
}

/* 依次展开一个目录路径(含其父链,同步 IO 逐个展开)。目录已不存在时返回 false。 */
static bool _fm_expand_path(const char *path)
{
    if (!path || !path[0] || !s_fm_root) return false;
    if (strncmp(path, TH_DIR, strlen(TH_DIR)) != 0) return false;

    th_node_t *cur = s_fm_root;
    const char *p = path + strlen(TH_DIR);
    char seg[EOS_FS_NAME_MAX];

    while (*p) {
        while (*p == '/') p++;
        if (!*p) break;
        size_t n = 0;
        while (*p && *p != '/' && n < sizeof(seg) - 1) seg[n++] = *p++;
        seg[n] = '\0';

        if (!cur->loaded) _fm_node_load(cur);
        cur->expanded = true;            /* 展开父目录才能继续向下找 */

        th_node_t *match = NULL;
        for (int i = 0; i < cur->child_count; i++) {
            if (cur->children[i].is_dir &&
                strcmp(cur->children[i].name, seg) == 0) {
                match = &cur->children[i];
                break;
            }
        }
        if (!match) return false;
        cur = match;
    }
    if (!cur->loaded) _fm_node_load(cur);
    cur->expanded = true;
    return true;
}

/* FM 打开时,依次展开历史记录的文件夹;目录已消失的记录移除 */
static void _fm_restore_expanded(void)
{
    if (!s_fm_root) return;
    for (int i = 0; i < s_fm_exp_count; ) {
        if (_fm_expand_path(s_fm_exp[i])) {
            i++;
        } else {
            _fm_exp_remove(s_fm_exp[i]);   /* 目录没了,清掉记录 */
        }
    }
}

/* Best-effort restore of the FM scroll position when it opens: walk the
 * anchor file path from the root, expand every directory on the way, then
 * scroll the flattened list so the anchor row is visible.  If the anchor or
 * any directory along the way no longer exists, give up. */
static void _fm_restore_position(void)
{
    if (!s_fm_root || s_fm_anchor[0] == '\0') return;
    if (strncmp(s_fm_anchor, TH_DIR, strlen(TH_DIR)) != 0) return;
    if (!_is_text_ext(_base(s_fm_anchor))) return;

    th_node_t *cur = s_fm_root;
    const char *p = s_fm_anchor + strlen(TH_DIR);
    char seg[EOS_FS_NAME_MAX];
    bool changed = false;

    while (*p) {
        while (*p == '/') p++;          /* skip slashes */
        if (!*p) break;
        size_t n = 0;
        while (*p && *p != '/' && n < sizeof(seg) - 1) seg[n++] = *p++;
        seg[n] = '\0';
        if (!*p) break;                  /* last segment = the text file */

        if (!cur->loaded) _fm_node_load(cur);
        th_node_t *match = NULL;
        for (int i = 0; i < cur->child_count; i++) {
            if (cur->children[i].is_dir &&
                strcmp(cur->children[i].name, seg) == 0) {
                match = &cur->children[i];
                break;
            }
        }
        if (!match) break;               /* dir gone: keep what we expanded */
        match->expanded = true;
        changed = true;
        cur = match;
    }

    if (changed) _fm_rebuild();

    /* scroll so the anchor file row is visible */
    for (int i = 0; i < s_fm_item_count; i++) {
        if (s_fm_items[i].node &&
            strcmp(s_fm_items[i].node->path, s_fm_anchor) == 0) {
            lv_obj_scroll_to_y(s_fm_list, i * TH_FM_ROW_H, LV_ANIM_OFF);
            break;
        }
    }
}

static void _fm_open(void)
{
    if (s_fm_open) return;
    s_fm_open = true;
    EOS_LOG_I("Texthub: fm open");

    /* mask: full-screen solid dark backdrop + tap-to-close */
    s_fm_mask = lv_obj_create(s_root);
    lv_obj_remove_style_all(s_fm_mask);
    lv_obj_set_size(s_fm_mask, 240, 240);
    lv_obj_set_pos(s_fm_mask, 0, 0);
    lv_obj_set_style_bg_color(s_fm_mask, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(s_fm_mask, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(s_fm_mask, 0, 0);
    lv_obj_clear_flag(s_fm_mask, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(s_fm_mask, _fm_close_cb, LV_EVENT_CLICKED, NULL);

    /* transparent container: the file tree renders directly on the solid
     * dark backdrop */
    s_fm_panel = lv_obj_create(s_fm_mask);
    lv_obj_remove_style_all(s_fm_panel);
    lv_obj_set_size(s_fm_panel, 212, 198);
    lv_obj_set_pos(s_fm_panel, 14, 30);
    lv_obj_set_style_bg_opa(s_fm_panel, LV_OPA_TRANSP, 0);
    lv_obj_set_style_radius(s_fm_panel, 0, 0);
    lv_obj_set_style_border_width(s_fm_panel, 0, 0);
    lv_obj_clear_flag(s_fm_panel, LV_OBJ_FLAG_SCROLLABLE);
    /* panel sits above the mask; no event bubbling to mask by default */

    /* header: path + close */
    s_fm_path = lv_label_create(s_fm_panel);
    eos_label_set_font_size(s_fm_path, EOS_FONT_SIZE_MICRO);
    lv_obj_set_style_text_color(s_fm_path, lv_color_hex(_UI_DIM), 0);
    lv_obj_set_size(s_fm_path, 140, 18);
    lv_obj_set_pos(s_fm_path, 14, 10);
    lv_label_set_long_mode(s_fm_path, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(s_fm_path, TH_DIR);
    lv_obj_remove_flag(s_fm_path, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(s_fm_path, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *close = lv_button_create(s_fm_panel);
    lv_obj_remove_style_all(close);
    lv_obj_set_size(close, 26, 22);
    lv_obj_set_pos(close, 176, 8);
    lv_obj_set_style_bg_color(close, lv_color_hex(_UI_TEXT), 0);
    lv_obj_set_style_bg_opa(close, 18, 0);
    lv_obj_set_style_radius(close, 8, 0);
    lv_obj_add_event_cb(close, _fm_close_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t *cl = lv_label_create(close);
    lv_obj_set_style_text_font(cl, &EOS_FONT_ICON, 0);
    lv_obj_set_style_text_color(cl, lv_color_hex(_UI_TEXT), 0);
    lv_label_set_text(cl, RI_CLOSE_FILL);
    lv_obj_center(cl);
    lv_obj_remove_flag(cl, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(cl, LV_OBJ_FLAG_SCROLLABLE);

    /* list */
    s_fm_list = lv_obj_create(s_fm_panel);
    lv_obj_remove_style_all(s_fm_list);
    lv_obj_set_size(s_fm_list, 200, 152);
    lv_obj_set_pos(s_fm_list, 6, 38);
    lv_obj_set_style_radius(s_fm_list, 10, 0);
    lv_obj_set_style_pad_all(s_fm_list, 0, 0);
    lv_obj_set_style_border_width(s_fm_list, 0, 0);
    lv_obj_add_flag(s_fm_list, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(s_fm_list, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_scroll_dir(s_fm_list, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(s_fm_list, LV_SCROLL_SNAP_NONE);
    lv_obj_set_style_bg_color(s_fm_list, lv_color_hex(_UI_DIM), LV_PART_SCROLLBAR);
    lv_obj_set_style_bg_opa(s_fm_list, LV_OPA_COVER, LV_PART_SCROLLBAR);
    lv_obj_set_style_radius(s_fm_list, 4, LV_PART_SCROLLBAR);

    /* root node */
    s_fm_root = (th_node_t *)eos_malloc_zeroed(sizeof(th_node_t));
    if (s_fm_root) {
        strncpy(s_fm_root->name, "texthub", sizeof(s_fm_root->name) - 1);
        strncpy(s_fm_root->path, TH_DIR, sizeof(s_fm_root->path) - 1);
        s_fm_root->is_dir = true;
        s_fm_root->expanded = true;    /* show root level immediately */
        _fm_node_load(s_fm_root);      /* load root lazily now */
    } else {
        EOS_LOG_E("Texthub: root alloc FAIL size=%u", (unsigned)sizeof(th_node_t));
    }

    /* 依次展开上次展开过的文件夹(最多 3 个,记录在历史文件) */
    _fm_restore_expanded();

    _fm_rebuild();

    /* restore FM scroll position from the last FM browse (best effort) */
    _fm_restore_position();
}

/* ------------------------------------------------------------------ */
/* UI                                                                 */
/* ------------------------------------------------------------------ */

/* Rounded button in capsule grey with an image icon (bottom capsule bar). */
static lv_obj_t *_make_img_btn(lv_obj_t *parent, int w, int h, uint32_t bg,
                               lv_align_t align, int x, int y,
                               lv_event_cb_t cb, const lv_image_dsc_t *img)
{
    lv_obj_t *btn = lv_button_create(parent);
    lv_obj_remove_style_all(btn);
    lv_obj_set_size(btn, w, h);
    lv_obj_set_style_bg_color(btn, lv_color_hex(bg), 0);
    lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(btn, 14, 0);
    lv_obj_set_style_border_width(btn, 0, 0);
    lv_obj_set_style_pad_all(btn, 0, 0);
    lv_obj_align(btn, align, x, y);
    lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, NULL);

    lv_obj_t *ic = lv_image_create(btn);
    lv_image_set_src(ic, img);
    lv_obj_center(ic);
    lv_obj_remove_flag(ic, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ic, LV_OBJ_FLAG_SCROLLABLE);
    return btn;
}

/* Small square-ish arrow button hugging the left/right edge (Album style). */
static lv_obj_t *_make_arrow(lv_obj_t *parent, lv_align_t align, int x, int y,
                             lv_event_cb_t cb, const char *icon)
{
    lv_obj_t *btn = lv_button_create(parent);
    lv_obj_remove_style_all(btn);
    lv_obj_set_size(btn, 30, 56);
    lv_obj_set_style_bg_color(btn, lv_color_hex(_UI_BTN_BG), 0);
    lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(btn, 6, 0);
    lv_obj_set_style_border_width(btn, 0, 0);
    lv_obj_set_style_pad_all(btn, 0, 0);
    lv_obj_align(btn, align, x, y);
    lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, NULL);

    lv_obj_t *lbl = lv_label_create(btn);
    lv_obj_set_style_text_font(lbl, &EOS_FONT_ICON, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(_UI_TEXT), 0);
    lv_label_set_text(lbl, icon);
    lv_obj_center(lbl);
    lv_obj_remove_flag(lbl, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(lbl, LV_OBJ_FLAG_SCROLLABLE);
    return btn;
}

/* Show / hide the capsule and the side arrows while the text scrolls. */
static void _ui_controls(bool vis)
{
    lv_obj_t *objs[] = { s_prev_btn, s_next_btn, s_capsule };
    for (unsigned i = 0; i < sizeof(objs) / sizeof(objs[0]); i++) {
        if (!objs[i]) continue;
        if (vis) lv_obj_remove_flag(objs[i], LV_OBJ_FLAG_HIDDEN);
        else     lv_obj_add_flag(objs[i], LV_OBJ_FLAG_HIDDEN);
    }
}

static void _card_scroll_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_SCROLL_BEGIN) {
        _ui_controls(false);            /* hide while reading / panning */
        return;
    }

    lv_obj_t *card = lv_event_get_target(e);
    if (s_restoring) return;            /* position restore in progress */

    _ui_controls(true);                 /* scroll stopped: bring back UI */

    /* keep reading position fresh (non-seg mode too) */
    _update_cur_pos();

    if (!s_seg_mode || s_fp == EOS_FILE_INVALID) return;

    int32_t sy = lv_obj_get_scroll_y(card);
    int32_t bottom = lv_obj_get_scroll_bottom(card);
    if (bottom <= 0) return;

    if (sy >= bottom - 6) {
        _seg_next();
    } else if (sy <= 0) {
        _seg_prev();
    }
}

static void _fm_btn_cb(lv_event_t *e)  { (void)e; _fm_open(); }
static void _prev_btn_cb(lv_event_t *e) { (void)e; _prev_file(); }
static void _next_btn_cb(lv_event_t *e) { (void)e; _next_file(); }

static void _build_ui(eos_activity_t *act)
{
    s_root = eos_activity_get_view(act);
    lv_obj_set_style_bg_color(s_root, lv_color_hex(_UI_BG), 0);
    eos_round_clip(s_root);

    /* floating filename, no chassis (Album style) */
    s_name = lv_label_create(s_root);
    eos_label_set_font_size(s_name, EOS_FONT_SIZE_MICRO);
    lv_obj_set_style_text_color(s_name, lv_color_hex(_UI_TEXT), 0);
    lv_obj_set_style_text_opa(s_name, LV_OPA_COVER, 0);
    lv_obj_set_width(s_name, TH_NAME_W);
    lv_obj_align(s_name, LV_ALIGN_TOP_MID, 0, 24);
    lv_label_set_long_mode(s_name, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(s_name, "Texthub");
    lv_obj_remove_flag(s_name, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(s_name, LV_OBJ_FLAG_SCROLLABLE);

    /* side arrows */
    s_prev_btn = _make_arrow(s_root, LV_ALIGN_LEFT_MID, 2, 0,
                             _prev_btn_cb, RI_ARROW_LEFT_S_LINE);
    s_next_btn = _make_arrow(s_root, LV_ALIGN_RIGHT_MID, -2, 0,
                             _next_btn_cb, RI_ARROW_RIGHT_S_LINE);

    /* text card */
    s_card = lv_obj_create(s_root);
    lv_obj_remove_style_all(s_card);
    lv_obj_set_size(s_card, 212, 132);
    lv_obj_set_pos(s_card, 14, 60);
    lv_obj_set_style_bg_color(s_card, lv_color_hex(_UI_CARD), 0);
    lv_obj_set_style_bg_opa(s_card, _UI_CARD_OPA, 0);
    lv_obj_set_style_radius(s_card, 12, 0);
    lv_obj_set_style_border_width(s_card, 0, 0);
    lv_obj_set_style_pad_all(s_card, 0, 0);
    lv_obj_add_flag(s_card, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(s_card, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(s_card, LV_DIR_VER);
    lv_obj_add_event_cb(s_card, _card_scroll_cb, LV_EVENT_SCROLL_BEGIN, NULL);
    lv_obj_add_event_cb(s_card, _card_scroll_cb, LV_EVENT_SCROLL_END, NULL);

    s_body = lv_label_create(s_card);
    eos_label_set_font_size(s_body, EOS_FONT_SIZE_MICRO);
    lv_obj_set_style_text_color(s_body, lv_color_hex(_UI_TEXT), 0);
    lv_obj_set_style_text_opa(s_body, 235, 0);
    lv_obj_set_style_text_align(s_body, LV_TEXT_ALIGN_LEFT, 0);
    lv_obj_set_width(s_body, 188);
    lv_obj_set_pos(s_body, 12, 8);
    lv_label_set_long_mode(s_body, LV_LABEL_LONG_MODE_WRAP);
    lv_label_set_text(s_body, "");
    lv_obj_remove_flag(s_body, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(s_body, LV_OBJ_FLAG_SCROLLABLE);

    /* bottom action capsule: delete + FM (Album style) */
    s_capsule = lv_obj_create(s_root);
    lv_obj_remove_style_all(s_capsule);
    lv_obj_set_size(s_capsule, 112, 56);
    lv_obj_set_style_bg_color(s_capsule, lv_color_hex(_UI_CAPSULE), 0);
    lv_obj_set_style_bg_opa(s_capsule, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(s_capsule, 28, 0);   /* pill shape */
    lv_obj_set_style_border_width(s_capsule, 0, 0);
    lv_obj_align(s_capsule, LV_ALIGN_BOTTOM_MID, 0, -12);

    s_trash_btn = _make_img_btn(s_capsule, 44, 40, _UI_CAPSULE,
                                LV_ALIGN_LEFT_MID, 8, 0,
                                _trash_cb, &eos_icon_delete);
    s_fm_btn = _make_img_btn(s_capsule, 44, 40, _UI_CAPSULE,
                             LV_ALIGN_RIGHT_MID, -8, 0,
                             _fm_btn_cb, &eos_icon_fm);

    /* bottom-left indicator */
    s_bottom = lv_label_create(s_root);
    eos_label_set_font_size(s_bottom, EOS_FONT_SIZE_TINY);
    lv_obj_set_style_text_color(s_bottom, lv_color_hex(_UI_DIM), 0);
    lv_obj_set_style_text_opa(s_bottom, 200, 0);
    lv_obj_set_size(s_bottom, 96, 12);
    lv_obj_align(s_bottom, LV_ALIGN_BOTTOM_LEFT, 8, -16);
    lv_label_set_long_mode(s_bottom, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(s_bottom, "");
    lv_obj_remove_flag(s_bottom, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(s_bottom, LV_OBJ_FLAG_SCROLLABLE);
}

/* ------------------------------------------------------------------ */
/* Lifecycle                                                          */
/* ------------------------------------------------------------------ */

static bool _on_swipe_back(eos_activity_t *self, lv_dir_t dir)
{
    (void)self;
    (void)dir;
    if (s_fm_open) { _fm_close(); return true; }
    return false;
}

static void _on_enter(eos_activity_t *act)
{
    s_act = act;
    _build_ui(act);

    /* try history first */
    if (eos_storage_is_file(TH_HIST_FILE)) {
        char *last = eos_storage_read_file(TH_HIST_FILE);
        if (last) {
            uint32_t pos = 0;
            char *nl = strchr(last, '\n');
            if (nl) {
                /* format: "<path>\n<pos>\n<fm_anchor>\n" */
                *nl = '\0';
                const char *ps = nl + 1;
                char *pe = strchr(ps, '\n');
                if (pe) *pe = '\0';
                pos = (uint32_t)strtoul(ps, NULL, 10);
                if (pos > 10000) pos = 10000;
                /* line 3: FM anchor (last file opened from the FM) */
                if (pe && pe[1] != '\0') {
                    char *l3 = pe + 1;
                    char *nl3 = strchr(l3, '\n');
                    if (nl3) *nl3 = '\0';
                    size_t l3len = strlen(l3);
                    while (l3len > 0 && (l3[l3len - 1] == '\r' ||
                                         l3[l3len - 1] == ' ')) {
                        l3[--l3len] = '\0';
                    }
                    if (l3len > 0 &&
                        strncmp(l3, TH_DIR "/", strlen(TH_DIR) + 1) == 0 &&
                        eos_storage_is_file(l3)) {
                        strncpy(s_fm_anchor, l3, sizeof(s_fm_anchor) - 1);
                        s_fm_anchor[sizeof(s_fm_anchor) - 1] = '\0';
                    }
                    /* line 4: 最近展开的文件夹(最多 3 个,| 分隔,行尾最新) */
                    if (nl3 && nl3[1] != '\0') {
                        char *l4 = nl3 + 1;
                        char *nl4 = strchr(l4, '\n');
                        if (nl4) *nl4 = '\0';
                        size_t l4len = strlen(l4);
                        while (l4len > 0 && (l4[l4len - 1] == '\r' ||
                                             l4[l4len - 1] == ' ')) {
                            l4[--l4len] = '\0';
                        }
                        _fm_exp_parse(l4);
                    }
                }
            } else {
                /* legacy format: bare path only (position = top) */
                size_t len = strlen(last);
                while (len > 0 && (last[len - 1] == '\n' || last[len - 1] == '\r')) {
                    last[--len] = '\0';
                }
            }
            size_t len = strlen(last);
            if (len > 1 && strncmp(last, TH_DIR "/", strlen(TH_DIR) + 1) == 0) {
                if (eos_storage_is_file(last) && _open_path(last)) {
                    eos_free(last);
                    _restore_pos(pos);
                    return;
                }
            }
            eos_free(last);
        }
    }
    /* no valid record -> File Manager */
    EOS_LOG_I("Texthub: no valid history, open FM");
    if (s_cur_path) {
        _free_text();
        eos_free(s_cur_path); s_cur_path = NULL;
        eos_free(s_cur_dir);  s_cur_dir  = NULL;
        s_cur_idx = s_cur_total = 0;
        lv_label_set_text(s_name, "Texthub");
        lv_label_set_text(s_bottom, "");
    }
    _show_centered_msg("NO FILES\nTap FM to browse");
    _fm_open();
}

static void _on_destroy(eos_activity_t *act)
{
    (void)act;
    /* persist the reading position (view is still valid during on_destroy) */
    if (s_cur_path) {
        _update_cur_pos();
        _write_history(s_cur_path, s_cur_pos);
    }
    _fm_close();
    _free_text();
    if (s_cur_path) { eos_free(s_cur_path); s_cur_path = NULL; }
    if (s_cur_dir)  { eos_free(s_cur_dir);  s_cur_dir  = NULL; }
    s_cur_idx = s_cur_total = 0;
    s_cur_pos = 0;
}

static const eos_activity_lifecycle_t s_lifecycle = {
    .on_enter      = _on_enter,
    .on_destroy    = _on_destroy,
    .on_swipe_back = _on_swipe_back,
};

void eos_texthub_enter(void)
{
    EOS_LOG_I("Texthub: enter");
    eos_activity_t *act = eos_activity_create(&s_lifecycle);
    eos_activity_set_type(act, EOS_ACTIVITY_TYPE_APP);
    eos_activity_set_app_header_visible(act, false);
    eos_activity_set_title(act, "Texthub");
    eos_activity_enter(act);
}
