#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@file gen_icon_def.py
@brief Auto-generate the ElenixOS icon definition header from a font file, with optional Unicode range

Usage:
    python gen_icon_def.py --ttf ./fonts/remixicon.ttf --out ./src/lang/fonts --start 0xE000 --end 0xEFFF

If parameters are not provided, defaults are:
    ../third_party/RemixIcon/fonts/remixicon.ttf
    ../src/lang/fonts/
"""

import os
import argparse
from fontTools.ttLib import TTFont
from datetime import datetime

def normalize_name(name: str) -> str:
    """Normalize a symbol name into C macro format."""
    invalid_chars = ['-', '.', ' ', '/', '+', '(', ')', '[', ']', '{', '}', '&', '%', '$', '@', '!', '?', ':', ';', ',']
    for ch in invalid_chars:
        name = name.replace(ch, '_')
    return name.upper()

def generate_icon_header(ttf_path: str, out_dir: str, start: int = None, end: int = None):
    """Generate the eos_icon.h file."""
    ttf_path = os.path.abspath(ttf_path)
    out_dir = os.path.abspath(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    font_name = os.path.splitext(os.path.basename(ttf_path))[0]
    output_path = os.path.join(out_dir, "eos_icon.h")
    date_str = datetime.now().strftime("%Y-%m-%d")

    # Open font file
    font = TTFont(ttf_path)

    # Build Unicode -> glyphName mapping
    unicode_map = {}
    for table in font["cmap"].tables:
        for codepoint, name in table.cmap.items():
            # Filter by optional Unicode range
            if start is not None and codepoint < start:
                continue
            if end is not None and codepoint > end:
                continue
            unicode_map[codepoint] = name

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"""/**
 * @file eos_icon.h
 * @brief Icon name to Unicode mapping
 *
 * This file is auto-generated by `gen_icon_def.py`.
 * Do not edit manually.
 * @date {date_str}
 */

#ifndef ELENIX_OS_ICON_H
#define ELENIX_OS_ICON_H

#ifdef __cplusplus
extern "C" {{
#endif

#include <stdint.h>
#include <stdbool.h>

/*
 * Font: {font_name} 「https://remixicon.com」
 * License: Apache License 2.0
 * Original source: https://github.com/Remix-Design/RemixIcon
 */
""")

        # Deduplicate macro names
        seen_macros = set()
        dup_count = 0
        for codepoint, name in sorted(unicode_map.items()):
            macro_name = normalize_name(name)
            if macro_name in seen_macros:
                dup_count += 1
                continue
            seen_macros.add(macro_name)
            f.write(f'#define RI_{macro_name} "\\u{codepoint:04X}"\n')

        f.write("""

void eos_icon_register(void);

#ifdef __cplusplus
}
#endif

#endif /* ELENIX_OS_ICON_H */
""")

    print(f"✅ Generated: {output_path}")
    print(f"🔢 Generated {len(seen_macros)} icon definitions, skipped {dup_count} duplicates.")

def main():
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    DEFAULT_TTF = os.path.normpath(os.path.join(BASE_DIR, "../third_party/RemixIcon/fonts/remixicon.ttf"))
    DEFAULT_OUT = os.path.normpath(os.path.join(BASE_DIR, "../src/lang/fonts"))

    parser = argparse.ArgumentParser(description="Generate LVGL icon definitions from TTF.")
    parser.add_argument("--ttf", help="Input TTF font path", default=DEFAULT_TTF)
    parser.add_argument("--out", help="Output directory", default=DEFAULT_OUT)
    parser.add_argument("--start", help="Unicode start codepoint (hex)", type=lambda x: int(x, 16))
    parser.add_argument("--end", help="Unicode end codepoint (hex)", type=lambda x: int(x, 16))
    args = parser.parse_args()

    print(f"🔍 Font: {args.ttf}")
    print(f"📂 Output directory: {args.out}")
    if args.start is not None or args.end is not None:
        print(f"🖤 Unicode generation range: {hex(args.start) if args.start else 'None'} ~ {hex(args.end) if args.end else 'None'}")

    generate_icon_header(args.ttf, args.out, args.start, args.end)

if __name__ == "__main__":
    main()
