#!/usr/bin/env python3
"""把 webp 图标转换为 LVGL ARGB8888 C 数组(嵌入式, 免运行时解码)。

用法:
    python3 scripts/icon/webp2c.py [--size 36] bluetooth wifi torch powersave
输出:
    resources/images/icon/eos_icon_<name>.c
"""
import argparse
import struct
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "resources" / "images" / "icon"

MAGIC = 0x19          # LV_IMAGE_HEADER_MAGIC
CF_ARGB8888 = 0x10    # LV_COLOR_FORMAT_ARGB8888


def gen_c(src: Path, name: str, size: int) -> str:
    im = Image.open(src).convert("RGBA")
    # 缩放到目标尺寸
    if im.size != (size, size):
        im = im.resize((size, size), Image.LANCZOS)
    pixels = im.load()

    data = bytearray()
    for y in range(size):
        for x in range(size):
            r, g, b, a = pixels[x, y]
            # ARGB8888 小端内存布局: [B, G, R, A]
            data += struct.pack("<I", (a << 24) | (r << 16) | (g << 8) | b)

    stride = size * 4
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in chunk) + ",")

    return f"""/* Auto-generated by scripts/icon/webp2c.py from {src.name} (size={size}x{size}) */
#include "lvgl.h"

const lv_image_dsc_t {name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_ARGB8888,
        .flags = 0,
        .w = {size},
        .h = {size},
        .stride = {stride},
        .reserved_2 = 0,
    }},
    .data_size = {len(data)},
    .data = (const uint8_t[]){{
{chr(10).join(lines)}
    }},
}};
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("names", nargs="+")
    ap.add_argument("--size", type=int, default=36)
    args = ap.parse_args()

    for name in args.names:
        src = ROOT / "resources" / "images" / "icon" / f"{name}.webp"
        if not src.exists():
            print(f"SKIP {name}: {src} 不存在")
            continue
        out = OUT_DIR / f"eos_icon_{name}.c"
        out.write_text(gen_c(src, f"eos_icon_{name}", args.size), encoding="utf-8")
        print(f"生成 {out} ({out.stat().st_size} B)")


if __name__ == "__main__":
    main()
