/**
 * @file eos_config.h
 * @brief System configuration entry point
 *
 * Do NOT edit this file for platform-specific settings.
 * Instead, create eos_platform_config.h in your platform's
 * config directory to override any kernel default.
 *
 * The include chain is:
 *   eos_config_internal.h   – enum constants
 *   eos_storage_paths.h     – storage directory layout
 *   eos_platform_config.h   – manual platform overrides       (optional)
 *   eos_config_gen.h       – generated by Kconfig menuconfig   (optional)
 *   eos_config_defaults.h   – kernel defaults
 */

#ifndef EOS_CONFIG_H
#define EOS_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include "eos_config_internal.h"
#include "eos_storage_paths.h"

#if __has_include("eos_platform_config.h")
#include "eos_platform_config.h"
#endif

#if __has_include("eos_config_gen.h")
#include "eos_config_gen.h"
#endif

#include "eos_config_defaults.h"

#include "eos_lvgl_requirements.h"

#ifdef __cplusplus
}
#endif

#endif /* EOS_CONFIG_H */
