/**
 * @file cos_config.h
 * @brief System configuration entry point
 *
 * Do NOT edit this file for platform-specific settings.
 * Instead, create cos_platform_config.h in your platform's
 * config directory to override any kernel default.
 *
 * The include chain is:
 *   cos_config_internal.h   – enum constants
 *   cos_storage_paths.h     – storage directory layout
 *   cos_platform_config.h   – manual platform overrides       (optional)
 *   cos_config_gen.h       – generated by Kconfig menuconfig   (optional)
 *   cos_config_defaults.h   – kernel defaults
 */

#ifndef COS_CONFIG_H
#define COS_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include "cos_config_internal.h"
#include "cos_storage_paths.h"

#if __has_include("cos_platform_config.h")
#include "cos_platform_config.h"
#endif

#if __has_include("cos_config_gen.h")
#include "cos_config_gen.h"
#endif

#include "cos_config_defaults.h"

#include "cos_lvgl_requirements.h"

#ifdef __cplusplus
}
#endif

#endif /* COS_CONFIG_H */
