/**
 * @file cos_config_defaults.h
 * @brief Kernel default configuration values
 *
 * This file provides FALLBACK defaults for every configurable option.
 * It uses the #ifndef pattern – if a value has already been set by
 * any platform layer (generated header, -D flag, cos_platform_config.h),
 * the default is skipped.
 *
 * This header knows NOTHING about CONFIG_ prefixes or any specific
 * Kconfig system.  It is purely a fallback-defaults provider.
 *
 * Override priority (highest to lowest):
 *   1. Compiler -D flags (e.g. CPPDEFINES)
 *   2. cos_platform_config.h       (manual, project-specific)
 *   3. cos_config_gen.h            (generated by a Kconfig system)
 *   4. This file                   (kernel fallback defaults)
 */

#ifndef COS_CONFIG_DEFAULTS_H
#define COS_CONFIG_DEFAULTS_H

/* Product identity -------------------------------------------*/

#ifndef CANTOMK6_WATCH_MARKETING_NAME
#define CANTOMK6_WATCH_MARKETING_NAME "Canto Mk.6"
#endif

#ifndef CANTOMK6_WATCH_MODEL_NUMBER
#define CANTOMK6_WATCH_MODEL_NUMBER "Canto Mk.6 1.28 Round"
#endif

/* Build / compilation mode -----------------------------------*/

#ifndef COS_COMPILE_MODE
#define COS_COMPILE_MODE DEBUG
#endif

/* Build profile: Dev vs Release.
 * Normally driven by the build system (CMake injects COS_BUILD_RELEASE=1
 * when `-DCOS_BUILD_RELEASE=1` or `CMAKE_BUILD_TYPE=Release`). This header
 * only provides a fallback so the symbol is always defined for #ifdef checks.
 * Release mode:
 *   - COS_LOG_DISABLE is set by the build system -> all COS_LOG_* become no-ops
 *   - the interactive USB-Serial shell listener task is skipped at startup
 * Shell CORE (cos_shell_init / cos_shell_exec) stays available in both modes
 * (AGENTS.md §9: shell must remain a rescue/debug entry). */
#ifndef COS_BUILD_RELEASE
#define COS_BUILD_RELEASE 0
#endif

/* Feature switches -------------------------------------------*/

#ifndef COS_ICON_STR_BUILD_IN
#define COS_ICON_STR_BUILD_IN 0
#endif

#ifndef COS_USE_VIRTUAL_DISPLAY
#define COS_USE_VIRTUAL_DISPLAY 1
#endif

/* Memory -----------------------------------------------------*/

#ifndef COS_MEM_ALLOC_PROVIDER
#define COS_MEM_ALLOC_PROVIDER COS_MEM_PROVIDER_STDLIB_CLIB
#endif

#ifndef COS_MEM_POOL_ALLOC_THRESHOLD
#if COS_MEM_ALLOC_PROVIDER == COS_MEM_PROVIDER_AUTO
#define COS_MEM_POOL_ALLOC_THRESHOLD (32 * 1024)
#else
#define COS_MEM_POOL_ALLOC_THRESHOLD 0
#endif
#endif

#if COS_MEM_ALLOC_PROVIDER == COS_MEM_PROVIDER_AUTO
#define COS_MEM_PROVIDER_AUTO_INCLUDE "mem_mgr.h"
#define COS_MEM_ALLOC_FAST malloc
#define COS_MEM_ALLOC_LARGE mem_mgr_alloc
#define COS_MEM_FREE_FAST free
#define COS_MEM_FREE_LARGE mem_mgr_free
#define COS_MEM_REALLOC_FAST realloc
#define COS_MEM_REALLOC_LARGE mem_mgr_realloc
#define COS_MEM_CALLOC_FAST calloc
#define COS_MEM_CALLOC_LARGE mem_mgr_calloc
#endif

#ifndef COS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE
#define COS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE (LV_USE_STDLIB_MALLOC == LV_STDLIB_CUSTOM)
#endif

#ifndef COS_MEM_TRACK_ENABLE
#define COS_MEM_TRACK_ENABLE 1
#endif

/* Image cache -------------------------------------------------*/

#ifndef COS_CACHE_ENABLE
#define COS_CACHE_ENABLE 1
#endif

#ifndef COS_CACHE_SIZE
#if defined(IMAGE_CACHE_IN_PSRAM_SIZE) && (IMAGE_CACHE_IN_PSRAM_SIZE > 0)
#define COS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_PSRAM_SIZE))
#elif defined(IMAGE_CACHE_IN_SRAM_SIZE) && (IMAGE_CACHE_IN_SRAM_SIZE > 0)
#define COS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_SRAM_SIZE))
#else
#define COS_CACHE_SIZE (128U * 1024U)
#endif
#endif

#ifndef COS_CACHE_HEADER_COUNT
#define COS_CACHE_HEADER_COUNT 16U
#endif

#ifndef COS_CACHE_USE_DEDICATED_MEM
#if defined(BSP_USING_PSRAM) || defined(IMAGE_CACHE_IN_PSRAM_SIZE)
#define COS_CACHE_USE_DEDICATED_MEM 1
#else
#define COS_CACHE_USE_DEDICATED_MEM 0
#endif
#endif

/* RTOS --------------------------------------------------------*/

#ifndef COS_RTOS_TYPE
#define COS_RTOS_TYPE COS_RTOS_BARE_METAL
#endif

/* Font --------------------------------------------------------*/

#ifndef COS_FONT_TYPE
#define COS_FONT_TYPE COS_FONT_TTF
#endif

/* 字体是否从 SD 卡加载(.ef 二进制):
 * 1 = 字体不编译进固件,开机从 /sdcard/font/ 下的 .ef 文件加载(C_MULTI 模式,真机);
 * 0 = 字体编译进固件(默认,推荐:Flash XIP 映射,不占运行时内存)。 */
#ifndef COS_FONT_SD_ENABLE
#define COS_FONT_SD_ENABLE 0
#endif

#ifndef COS_FONT_CFG_LARGE_SIZE
#define COS_FONT_CFG_LARGE_SIZE 30
#endif

#ifndef COS_FONT_CFG_MEDIUM_SIZE
#define COS_FONT_CFG_MEDIUM_SIZE (COS_FONT_CFG_LARGE_SIZE - 4)
#endif

#ifndef COS_FONT_CFG_SMALL_SIZE
#define COS_FONT_CFG_SMALL_SIZE (COS_FONT_CFG_MEDIUM_SIZE - 6) /* 20px:整体小两号,见 cos_font_jbm_20 */
#endif

/* 16px 与 20px 之间的中档字号(17..19px 请求用 18px 字体),见 cos_font_jbm_18 */
#ifndef COS_FONT_CFG_TALL_SIZE
#define COS_FONT_CFG_TALL_SIZE 18
#endif

/* 小字号档(12..15px 用 13px 字体;<=11px 用 10px 字体),由 cos_font_c_multi.c 按区间选择 */
#ifndef COS_FONT_CFG_MICRO_SIZE
#define COS_FONT_CFG_MICRO_SIZE 13
#endif

#ifndef COS_FONT_CFG_TINY_SIZE
#define COS_FONT_CFG_TINY_SIZE 10
#endif

#if COS_FONT_TYPE == COS_FONT_C_MULTI

#ifndef COS_ENABLE_CHINESE_FONT
#define COS_ENABLE_CHINESE_FONT 1
#endif

#if COS_ENABLE_CHINESE_FONT
/* JetBrainsMono-Medium (拉丁/数字/符号, 清晰等宽) + 内置 fallback=source_han_sans_*(中文) */
#define COS_FONT_LARGE_NAME cos_font_jbm_30
#define COS_FONT_MEDIUM_NAME cos_font_jbm_26
#define COS_FONT_SMALL_NAME cos_font_jbm_20
#define COS_FONT_TALL_NAME cos_font_jbm_18
#define COS_FONT_EXTRA_SMALL_NAME cos_font_jbm_16
#define COS_FONT_MICRO_NAME cos_font_jbm_13
#define COS_FONT_TINY_NAME cos_font_jbm_10
#else
#define COS_FONT_LARGE_NAME lv_font_montserrat_30
#define COS_FONT_MEDIUM_NAME lv_font_montserrat_30
#define COS_FONT_SMALL_NAME lv_font_montserrat_30
#define COS_FONT_TALL_NAME cos_font_jbm_18
#define COS_FONT_EXTRA_SMALL_NAME cos_font_jbm_16
#define COS_FONT_MICRO_NAME cos_font_jbm_13
#define COS_FONT_TINY_NAME cos_font_jbm_10
#endif

#elif COS_FONT_TYPE == COS_FONT_TTF

#ifndef COS_FONT_TTF_TYPE
#define COS_FONT_TTF_TYPE COS_FONT_TTF_FILE
#endif

#if COS_FONT_TTF_TYPE == COS_FONT_TTF_DATA
#define COS_FONT_TTF_DATA_NAME SourceHanSansSC_12M
#define COS_FONT_TTF_DATA_SIZE SourceHanSansSC_12M_size
#elif COS_FONT_TTF_TYPE == COS_FONT_TTF_FILE
#if !defined(COS_FONT_TTF_FILE_PATH)
/* 字体从外部 SD 卡读取(/sdcard/font/font.ttf),不再依赖内置资源路径 */
#define COS_FONT_TTF_FILE_PATH COS_SD_ROOT_DIR "font/font.ttf"
#endif
#endif

#ifndef COS_FONT_TTF_ENABLE_EXTENDED
#define COS_FONT_TTF_ENABLE_EXTENDED 0
#endif

#if COS_FONT_TTF_ENABLE_EXTENDED
#ifndef COS_FONT_TTF_KERNING
#define COS_FONT_TTF_KERNING 0
#endif
#ifndef COS_FONT_TTF_CACHE_SIZE
#define COS_FONT_TTF_CACHE_SIZE 256
#endif
#endif

#endif /* COS_FONT_TYPE */

/* Display -----------------------------------------------------*/

#ifndef COS_DISPLAY_WIDTH
#define COS_DISPLAY_WIDTH 390
#endif

#ifndef COS_DISPLAY_HEIGHT
#define COS_DISPLAY_HEIGHT 450
#endif

#ifndef COS_DISPLAY_RADIUS
#define COS_DISPLAY_RADIUS 80
#endif

#ifndef COS_DISPLAY_BRIGHTNESS_MIN
#define COS_DISPLAY_BRIGHTNESS_MIN 5
#endif

#ifndef COS_DISPLAY_BRIGHTNESS_MAX
#define COS_DISPLAY_BRIGHTNESS_MAX 100
#endif

/* File system -------------------------------------------------*/

#ifndef COS_SYS_ROOT_DIR
#define COS_SYS_ROOT_DIR "/"
#endif

#ifndef COS_FS_TYPE
#define COS_FS_TYPE COS_FS_POSIX
#endif

#if COS_FS_TYPE == COS_FS_CUSTOM
#define COS_FS_FILE_TYPE void *
#define COS_FS_DIR_TYPE void *
#define COS_FILE_INVALID NULL
#define COS_DIR_INVALID NULL
#endif

#ifndef COS_FS_PATH_MAX
#define COS_FS_PATH_MAX 256
#endif

/* Maximum length of a single path component / file name (bytes).
 * Directory entry names, package IDs, etc. are stored in buffers of this
 * size, so a full path built from such a name needs PATH_MAX + NAME_MAX. */
#ifndef COS_FS_NAME_MAX
#define COS_FS_NAME_MAX 256
#endif

#ifndef COS_LVGL_FS_LETTER
#define COS_LVGL_FS_LETTER 'Z'
#endif

#ifndef COS_DFW_ENABLE
#define COS_DFW_ENABLE 0
#endif

/* Language ----------------------------------------------------*/

#ifndef COS_CONFIG_DEFAULT_LANGUAGE
#define COS_CONFIG_DEFAULT_LANGUAGE 0
#endif

/* Miscellaneous -----------------------------------------------*/

/* Built-in test app (sys.test). Disabled by default: it is only useful
 * during development and shows up in app list / launcher. */
#ifndef COS_ENABLE_TEST_APP
#define COS_ENABLE_TEST_APP 0
#endif

/* Logging -----------------------------------------------------*/

#ifndef COS_USE_ASSERT
#define COS_USE_ASSERT 1
#endif

#ifndef COS_ASSERT_HANDLER
#define COS_ASSERT_HANDLER __builtin_trap();
#endif

#ifndef COS_LOG_USE_COLOR
#define COS_LOG_USE_COLOR 0
#endif

#ifndef COS_LOG_MAX_LISTENERS
#define COS_LOG_MAX_LISTENERS 8
#endif

#ifndef COS_LOG_ENABLE_STD
#define COS_LOG_ENABLE_STD 1
#endif

#endif /* COS_CONFIG_DEFAULTS_H */
