/**
 * @file eos_config_defaults.h
 * @brief Kernel default configuration values
 *
 * This file provides FALLBACK defaults for every configurable option.
 * It uses the #ifndef pattern – if a value has already been set by
 * any platform layer (generated header, -D flag, eos_platform_config.h),
 * the default is skipped.
 *
 * This header knows NOTHING about CONFIG_ prefixes or any specific
 * Kconfig system.  It is purely a fallback-defaults provider.
 *
 * Override priority (highest to lowest):
 *   1. Compiler -D flags (e.g. CPPDEFINES)
 *   2. eos_platform_config.h       (manual, project-specific)
 *   3. eos_config_gen.h            (generated by a Kconfig system)
 *   4. This file                   (kernel fallback defaults)
 */

#ifndef EOS_CONFIG_DEFAULTS_H
#define EOS_CONFIG_DEFAULTS_H

/* Product identity -------------------------------------------*/

#ifndef ELENIX_WATCH_MARKETING_NAME
#define ELENIX_WATCH_MARKETING_NAME "Elenix Watch"
#endif

#ifndef ELENIX_WATCH_MODEL_NUMBER
#define ELENIX_WATCH_MODEL_NUMBER "S2508(0)"
#endif

/* Build / compilation mode -----------------------------------*/

#ifndef EOS_COMPILE_MODE
#define EOS_COMPILE_MODE DEBUG
#endif

/* Feature switches -------------------------------------------*/

#ifndef EOS_ICON_STR_BUILD_IN
#define EOS_ICON_STR_BUILD_IN 0
#endif

#ifndef EOS_USE_VIRTUAL_DISPLAY
#define EOS_USE_VIRTUAL_DISPLAY 1
#endif

/* Memory -----------------------------------------------------*/

#ifndef EOS_MEM_ALLOC_PROVIDER
#define EOS_MEM_ALLOC_PROVIDER EOS_MEM_PROVIDER_STDLIB_CLIB
#endif

#ifndef EOS_MEM_POOL_ALLOC_THRESHOLD
#if EOS_MEM_ALLOC_PROVIDER == EOS_MEM_PROVIDER_AUTO
#define EOS_MEM_POOL_ALLOC_THRESHOLD (32 * 1024)
#else
#define EOS_MEM_POOL_ALLOC_THRESHOLD 0
#endif
#endif

#if EOS_MEM_ALLOC_PROVIDER == EOS_MEM_PROVIDER_AUTO
#define EOS_MEM_PROVIDER_AUTO_INCLUDE "mem_mgr.h"
#define EOS_MEM_ALLOC_FAST malloc
#define EOS_MEM_ALLOC_LARGE mem_mgr_alloc
#define EOS_MEM_FREE_FAST free
#define EOS_MEM_FREE_LARGE mem_mgr_free
#define EOS_MEM_REALLOC_FAST realloc
#define EOS_MEM_REALLOC_LARGE mem_mgr_realloc
#define EOS_MEM_CALLOC_FAST calloc
#define EOS_MEM_CALLOC_LARGE mem_mgr_calloc
#endif

#ifndef EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE
#define EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE (LV_USE_STDLIB_MALLOC == LV_STDLIB_CUSTOM)
#endif

#ifndef EOS_MEM_TRACK_ENABLE
#define EOS_MEM_TRACK_ENABLE 1
#endif

/* Image cache -------------------------------------------------*/

#ifndef EOS_CACHE_ENABLE
#define EOS_CACHE_ENABLE 1
#endif

#ifndef EOS_CACHE_SIZE
#if defined(IMAGE_CACHE_IN_PSRAM_SIZE) && (IMAGE_CACHE_IN_PSRAM_SIZE > 0)
#define EOS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_PSRAM_SIZE))
#elif defined(IMAGE_CACHE_IN_SRAM_SIZE) && (IMAGE_CACHE_IN_SRAM_SIZE > 0)
#define EOS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_SRAM_SIZE))
#else
#define EOS_CACHE_SIZE (128U * 1024U)
#endif
#endif

#ifndef EOS_CACHE_HEADER_COUNT
#define EOS_CACHE_HEADER_COUNT 16U
#endif

#ifndef EOS_CACHE_USE_DEDICATED_MEM
#if defined(BSP_USING_PSRAM) || defined(IMAGE_CACHE_IN_PSRAM_SIZE)
#define EOS_CACHE_USE_DEDICATED_MEM 1
#else
#define EOS_CACHE_USE_DEDICATED_MEM 0
#endif
#endif

/* RTOS --------------------------------------------------------*/

#ifndef EOS_RTOS_TYPE
#define EOS_RTOS_TYPE EOS_RTOS_BARE_METAL
#endif

/* Font --------------------------------------------------------*/

#ifndef EOS_FONT_TYPE
#define EOS_FONT_TYPE EOS_FONT_TTF
#endif

#ifndef EOS_FONT_CFG_LARGE_SIZE
#define EOS_FONT_CFG_LARGE_SIZE 30
#endif

#ifndef EOS_FONT_CFG_MEDIUM_SIZE
#define EOS_FONT_CFG_MEDIUM_SIZE (EOS_FONT_CFG_LARGE_SIZE - 4)
#endif

#ifndef EOS_FONT_CFG_SMALL_SIZE
#define EOS_FONT_CFG_SMALL_SIZE (EOS_FONT_CFG_MEDIUM_SIZE - 4)
#endif

#if EOS_FONT_TYPE == EOS_FONT_C_MULTI

#ifndef EOS_ENABLE_CHINESE_FONT
#define EOS_ENABLE_CHINESE_FONT 1
#endif

#if EOS_ENABLE_CHINESE_FONT
#define EOS_FONT_LARGE_NAME source_han_sans_30
#define EOS_FONT_MEDIUM_NAME source_han_sans_26
#define EOS_FONT_SMALL_NAME source_han_sans_22
#else
#define EOS_FONT_LARGE_NAME lv_font_montserrat_30
#define EOS_FONT_MEDIUM_NAME lv_font_montserrat_30
#define EOS_FONT_SMALL_NAME lv_font_montserrat_30
#endif

#elif EOS_FONT_TYPE == EOS_FONT_TTF

#ifndef EOS_FONT_TTF_TYPE
#define EOS_FONT_TTF_TYPE EOS_FONT_TTF_FILE
#endif

#if EOS_FONT_TTF_TYPE == EOS_FONT_TTF_DATA
#define EOS_FONT_TTF_DATA_NAME SourceHanSansSC_12M
#define EOS_FONT_TTF_DATA_SIZE SourceHanSansSC_12M_size
#elif EOS_FONT_TTF_TYPE == EOS_FONT_TTF_FILE
#if !defined(EOS_FONT_TTF_FILE_PATH)
#define EOS_FONT_TTF_FILE_PATH EOS_SYS_RES_FONT_DIR "font.ttf"
#endif
#endif

#ifndef EOS_FONT_TTF_ENABLE_EXTENDED
#define EOS_FONT_TTF_ENABLE_EXTENDED 0
#endif

#if EOS_FONT_TTF_ENABLE_EXTENDED
#ifndef EOS_FONT_TTF_KERNING
#define EOS_FONT_TTF_KERNING 0
#endif
#ifndef EOS_FONT_TTF_CACHE_SIZE
#define EOS_FONT_TTF_CACHE_SIZE 256
#endif
#endif

#endif /* EOS_FONT_TYPE */

/* Display -----------------------------------------------------*/

#ifndef EOS_DISPLAY_WIDTH
#define EOS_DISPLAY_WIDTH 390
#endif

#ifndef EOS_DISPLAY_HEIGHT
#define EOS_DISPLAY_HEIGHT 450
#endif

#ifndef EOS_DISPLAY_RADIUS
#define EOS_DISPLAY_RADIUS 80
#endif

#ifndef EOS_DISPLAY_BRIGHTNESS_MIN
#define EOS_DISPLAY_BRIGHTNESS_MIN 5
#endif

#ifndef EOS_DISPLAY_BRIGHTNESS_MAX
#define EOS_DISPLAY_BRIGHTNESS_MAX 100
#endif

/* File system -------------------------------------------------*/

#ifndef EOS_SYS_ROOT_DIR
#define EOS_SYS_ROOT_DIR "/"
#endif

#ifndef EOS_FS_TYPE
#define EOS_FS_TYPE EOS_FS_POSIX
#endif

#if EOS_FS_TYPE == EOS_FS_CUSTOM
#define EOS_FS_FILE_TYPE void *
#define EOS_FS_DIR_TYPE void *
#define EOS_FILE_INVALID NULL
#define EOS_DIR_INVALID NULL
#endif

#ifndef EOS_FS_PATH_MAX
#define EOS_FS_PATH_MAX 256
#endif

#ifndef EOS_LVGL_FS_LETTER
#define EOS_LVGL_FS_LETTER 'Z'
#endif

#ifndef EOS_DFW_ENABLE
#define EOS_DFW_ENABLE 0
#endif

/* Language ----------------------------------------------------*/

#ifndef EOS_CONFIG_DEFAULT_LANGUAGE
#define EOS_CONFIG_DEFAULT_LANGUAGE 0
#endif

/* Miscellaneous -----------------------------------------------*/

#ifndef EOS_ENABLE_TEST_APP
#define EOS_ENABLE_TEST_APP 1
#endif

/* Logging -----------------------------------------------------*/

#ifndef EOS_USE_ASSERT
#define EOS_USE_ASSERT 1
#endif

#ifndef EOS_ASSERT_HANDLER
#define EOS_ASSERT_HANDLER __builtin_trap();
#endif

#ifndef EOS_LOG_USE_COLOR
#define EOS_LOG_USE_COLOR 0
#endif

#ifndef EOS_LOG_MAX_LISTENERS
#define EOS_LOG_MAX_LISTENERS 8
#endif

#ifndef EOS_LOG_ENABLE_STD
#define EOS_LOG_ENABLE_STD 1
#endif

#endif /* EOS_CONFIG_DEFAULTS_H */
