/**
 * @file sni_lv_types.c
 * @brief LVGL type table
 **************************************************************************
 * This file is auto-generated by gen_sni_lv_types.py. Do not edit manually.
 **************************************************************************
 */

#include "sni_lv_types.h"

/* Includes ---------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include "sni_types.h"
#include "sni_type_bridge.h"
#include "lvgl.h"

/************************** Property tables **************************/

const sni_val_prop_t lv_anim_bezier3_para_props[] = {
    {
        .name = "x1",
        .type = SNI_T_INT16,
        .offset = offsetof(lv_anim_bezier3_para_t, x1),
        .bit_width = 0,
    },
    {
        .name = "y1",
        .type = SNI_T_INT16,
        .offset = offsetof(lv_anim_bezier3_para_t, y1),
        .bit_width = 0,
    },
    {
        .name = "x2",
        .type = SNI_T_INT16,
        .offset = offsetof(lv_anim_bezier3_para_t, x2),
        .bit_width = 0,
    },
    {
        .name = "y2",
        .type = SNI_T_INT16,
        .offset = offsetof(lv_anim_bezier3_para_t, y2),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_anim_bezier3_para_prop = {
    .type = SNI_V_LV_ANIM_BEZIER3_PARA,
    .prop_count = 4,
    .props = lv_anim_bezier3_para_props,
};

const sni_val_prop_t lv_area_props[] = {
    {
        .name = "x1",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, x1),
        .bit_width = 0,
    },
    {
        .name = "y1",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, y1),
        .bit_width = 0,
    },
    {
        .name = "x2",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, x2),
        .bit_width = 0,
    },
    {
        .name = "y2",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, y2),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_area_prop = {
    .type = SNI_V_LV_AREA,
    .prop_count = 4,
    .props = lv_area_props,
};

const sni_val_prop_t lv_color16_props[] = {
    {
        .name = "blue",
        .type = SNI_T_UINT16,
        .offset = 0,
        .bit_width = 5,
    },
    {
        .name = "green",
        .type = SNI_T_UINT16,
        .offset = 0,
        .bit_width = 6,
    },
    {
        .name = "red",
        .type = SNI_T_UINT16,
        .offset = 0,
        .bit_width = 5,
    },
};

const sni_val_obj_t lv_color16_prop = {
    .type = SNI_V_LV_COLOR16,
    .prop_count = 3,
    .props = lv_color16_props,
};

const sni_val_prop_t lv_color16a_props[] = {
    {
        .name = "lumi",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color16a_t, lumi),
        .bit_width = 0,
    },
    {
        .name = "alpha",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color16a_t, alpha),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_color16a_prop = {
    .type = SNI_V_LV_COLOR16A,
    .prop_count = 2,
    .props = lv_color16a_props,
};

const sni_val_prop_t lv_color32_props[] = {
    {
        .name = "blue",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, blue),
        .bit_width = 0,
    },
    {
        .name = "green",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, green),
        .bit_width = 0,
    },
    {
        .name = "red",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, red),
        .bit_width = 0,
    },
    {
        .name = "alpha",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, alpha),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_color32_prop = {
    .type = SNI_V_LV_COLOR32,
    .prop_count = 4,
    .props = lv_color32_props,
};

const sni_val_prop_t lv_color_hsv_props[] = {
    {
        .name = "h",
        .type = SNI_T_UINT16,
        .offset = offsetof(lv_color_hsv_t, h),
        .bit_width = 0,
    },
    {
        .name = "s",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_hsv_t, s),
        .bit_width = 0,
    },
    {
        .name = "v",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_hsv_t, v),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_color_hsv_prop = {
    .type = SNI_V_LV_COLOR_HSV,
    .prop_count = 3,
    .props = lv_color_hsv_props,
};

const sni_val_prop_t lv_color_props[] = {
    {
        .name = "blue",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, blue),
        .bit_width = 0,
    },
    {
        .name = "green",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, green),
        .bit_width = 0,
    },
    {
        .name = "red",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, red),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_color_prop = {
    .type = SNI_V_LV_COLOR,
    .prop_count = 3,
    .props = lv_color_props,
};

const sni_val_prop_t lv_grad_color_props[] = {
    {
        .name = "blue",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, blue),
        .bit_width = 0,
    },
    {
        .name = "green",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, green),
        .bit_width = 0,
    },
    {
        .name = "red",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, red),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_grad_color_prop = {
    .type = SNI_V_LV_GRAD_COLOR,
    .prop_count = 3,
    .props = lv_grad_color_props,
};

const sni_val_prop_t lv_gradient_stop_props[] = {
    {
        .name = "color",
        .type = SNI_V_LV_COLOR,
        .offset = offsetof(lv_gradient_stop_t, color),
        .bit_width = 0,
    },
    {
        .name = "opa",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_gradient_stop_t, opa),
        .bit_width = 0,
    },
    {
        .name = "frac",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_gradient_stop_t, frac),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_gradient_stop_prop = {
    .type = SNI_V_LV_GRADIENT_STOP,
    .prop_count = 3,
    .props = lv_gradient_stop_props,
};

const sni_val_prop_t lv_point_precise_props[] = {
    {
        .name = "x",
        .type = SNI_T_DOUBLE,
        .offset = offsetof(lv_point_precise_t, x),
        .bit_width = 0,
    },
    {
        .name = "y",
        .type = SNI_T_DOUBLE,
        .offset = offsetof(lv_point_precise_t, y),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_point_precise_prop = {
    .type = SNI_V_LV_POINT_PRECISE,
    .prop_count = 2,
    .props = lv_point_precise_props,
};

const sni_val_prop_t lv_point_props[] = {
    {
        .name = "x",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_point_t, x),
        .bit_width = 0,
    },
    {
        .name = "y",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_point_t, y),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_point_prop = {
    .type = SNI_V_LV_POINT,
    .prop_count = 2,
    .props = lv_point_props,
};

const sni_val_prop_t lv_sqrt_res_props[] = {
    {
        .name = "i",
        .type = SNI_T_UINT16,
        .offset = offsetof(lv_sqrt_res_t, i),
        .bit_width = 0,
    },
    {
        .name = "f",
        .type = SNI_T_UINT16,
        .offset = offsetof(lv_sqrt_res_t, f),
        .bit_width = 0,
    },
};

const sni_val_obj_t lv_sqrt_res_prop = {
    .type = SNI_V_LV_SQRT_RES,
    .prop_count = 2,
    .props = lv_sqrt_res_props,
};

/************************** Registry **************************/

const sni_val_obj_t *sni_lv_types[] = {
    &lv_anim_bezier3_para_prop,
    &lv_area_prop,
    &lv_color16_prop,
    &lv_color16a_prop,
    &lv_color32_prop,
    &lv_color_hsv_prop,
    &lv_color_prop,
    &lv_grad_color_prop,
    &lv_gradient_stop_prop,
    &lv_point_precise_prop,
    &lv_point_prop,
    &lv_sqrt_res_prop,
};

const size_t sni_lv_types_count = sizeof(sni_lv_types) / sizeof(sni_lv_types[0]);

/************************** Initialization **************************/
void sni_lv_types_init(void)
{
    for (size_t i = 0; i < sni_lv_types_count; i++)
    {
        sni_tb_register_val_obj(sni_lv_types[i]);
    }
}
